import { ShoppingCategory, PantryItem, ShoppingItem, Recipe, Expense, MealPlanEntry, PricingPlan, HouseholdMember, NotificationItem } from '@/types';

export const shoppingCategories: { name: ShoppingCategory; icon: string }[] = [
  { name: 'Fruit and Vegetables', icon: '🥬' },
  { name: 'Meat and Poultry', icon: '🍗' },
  { name: 'Bakery', icon: '🍞' },
  { name: 'Dairy and Eggs', icon: '🥛' },
  { name: 'Frozen Foods', icon: '🧊' },
  { name: 'Pantry Staples', icon: '🥫' },
  { name: 'Breakfast', icon: '🍳' },
  { name: 'Snacks', icon: '🍪' },
  { name: 'Drinks', icon: '🥤' },
  { name: 'Household Cleaning', icon: '🧹' },
  { name: 'Toiletries', icon: '🧴' },
  { name: 'Baby', icon: '🍼' },
  { name: 'Pet', icon: '🐾' },
  { name: 'Other', icon: '🛒' },
];

export const shoppingItems: ShoppingItem[] = [
  { id: '1', name: 'Milk 2L', category: 'Dairy and Eggs', quantity: 2, unit: 'L', price: 36.99, checked: false },
  { id: '2', name: 'Brown Bread', category: 'Bakery', quantity: 1, unit: 'loaf', price: 16.99, checked: true },
  { id: '3', name: 'Maize Meal 5kg', category: 'Pantry Staples', quantity: 1, unit: 'bag', price: 64.99, checked: false },
  { id: '4', name: 'Chicken portions 1kg', category: 'Meat and Poultry', quantity: 1, unit: 'kg', price: 89.99, checked: false },
  { id: '5', name: 'Rice 2kg', category: 'Pantry Staples', quantity: 1, unit: 'bag', price: 49.99, checked: true },
  { id: '6', name: 'Tomatoes 1kg', category: 'Fruit and Vegetables', quantity: 1, unit: 'kg', price: 24.99, checked: false },
  { id: '7', name: 'Potatoes 5kg', category: 'Fruit and Vegetables', quantity: 1, unit: 'bag', price: 54.99, checked: false },
  { id: '8', name: 'Eggs (dozen)', category: 'Dairy and Eggs', quantity: 1, unit: 'dozen', price: 39.99, checked: false },
  { id: '9', name: 'Cooking oil 2L', category: 'Pantry Staples', quantity: 1, unit: 'bottle', price: 79.99, checked: false },
  { id: '10', name: 'Rooibos Tea 100s', category: 'Drinks', quantity: 1, unit: 'box', price: 44.99, checked: true },
  { id: '11', name: 'Coffee 200g', category: 'Drinks', quantity: 1, unit: 'jar', price: 69.99, checked: false },
  { id: '12', name: 'Onions 1kg', category: 'Fruit and Vegetables', quantity: 1, unit: 'kg', price: 19.99, checked: false },
  { id: '13', name: 'Sugar 2kg', category: 'Pantry Staples', quantity: 1, unit: 'bag', price: 42.99, checked: false },
  { id: '14', name: 'Boerewors 500g', category: 'Meat and Poultry', quantity: 1, unit: 'pack', price: 59.99, checked: false },
  { id: '15', name: 'Mince 500g', category: 'Meat and Poultry', quantity: 1, unit: 'pack', price: 54.99, checked: false },
];

export const pantryItems: PantryItem[] = [
  { id: '1', name: 'Milk 2L', category: 'Dairy and Eggs', quantity: 2, unit: 'L', expiryDate: '2026-07-20', lowStock: false, price: 36.99 },
  { id: '2', name: 'Brown Bread', category: 'Bakery', quantity: 1, unit: 'loaf', expiryDate: '2026-07-19', lowStock: false, price: 16.99 },
  { id: '3', name: 'Maize Meal 5kg', category: 'Pantry Staples', quantity: 3, unit: 'kg', expiryDate: '2026-10-15', lowStock: false, price: 64.99 },
  { id: '4', name: 'Chicken portions', category: 'Meat and Poultry', quantity: 500, unit: 'g', expiryDate: '2026-07-18', lowStock: false, price: 89.99 },
  { id: '5', name: 'Rice', category: 'Pantry Staples', quantity: 1, unit: 'kg', expiryDate: '2026-12-01', lowStock: true, price: 49.99 },
  { id: '6', name: 'Tomatoes', category: 'Fruit and Vegetables', quantity: 4, unit: 'pcs', expiryDate: '2026-07-18', lowStock: false, price: 24.99 },
  { id: '7', name: 'Eggs', category: 'Dairy and Eggs', quantity: 3, unit: 'pcs', expiryDate: '2026-07-25', lowStock: true, price: 39.99 },
  { id: '8', name: 'Cooking oil', category: 'Pantry Staples', quantity: 1, unit: 'L', expiryDate: '2026-11-30', lowStock: false, price: 79.99 },
  { id: '9', name: 'Onions', category: 'Fruit and Vegetables', quantity: 5, unit: 'pcs', expiryDate: '2026-07-22', lowStock: false, price: 19.99 },
  { id: '10', name: 'Coffee 200g', category: 'Drinks', quantity: 1, unit: 'jar', expiryDate: '2026-09-01', lowStock: true, price: 69.99 },
];

export const recipes: Recipe[] = [
  {
    id: '1',
    name: 'Creamy Chicken Pasta',
    image: 'pasta',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    estimatedCost: 145,
    availableIngredients: ['Chicken', 'Pasta', 'Cooking oil', 'Onions'],
    missingIngredients: ['Cream', 'Garlic', 'Parmesan'],
    steps: [
      'Boil pasta in salted water until al dente, then drain.',
      'Season chicken with salt and pepper, then pan-sear in oil until golden.',
      'Sauté sliced onions and garlic until soft and fragrant.',
      'Slice the cooked chicken and return to the pan.',
      'Pour in cream and grated parmesan, stirring until smooth.',
      'Toss the cooked pasta in the creamy sauce and serve hot.',
    ],
  },
  {
    id: '2',
    name: 'Chicken and Vegetable Stew',
    image: 'stew',
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    estimatedCost: 120,
    availableIngredients: ['Chicken', 'Potatoes', 'Tomatoes', 'Onions', 'Cooking oil'],
    missingIngredients: ['Carrots', 'Garlic', 'Stock cubes'],
    steps: [
      'Brown chicken pieces in a large pot with heated oil.',
      'Add chopped onions and garlic, frying until soft.',
      'Stir in chopped tomatoes and cook for 5 minutes.',
      'Add peeled potatoes and carrots to the pot.',
      'Pour in stock and simmer for 40 minutes until tender.',
      'Season to taste and serve with rice or pap.',
    ],
  },
  {
    id: '3',
    name: 'Pap and Tomato Relish',
    image: 'pap',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    estimatedCost: 55,
    availableIngredients: ['Maize meal', 'Tomatoes', 'Onions', 'Cooking oil'],
    missingIngredients: ['Green pepper', 'Chilli'],
    steps: [
      'Bring 4 cups of water to a boil in a pot.',
      'Slowly whisk in maize meal, stirring to avoid lumps.',
      'Reduce heat and cook covered for 15 minutes, stirring occasionally.',
      'For the relish, fry chopped onions and tomatoes in oil.',
      'Add diced green pepper and chilli, simmering for 10 minutes.',
      'Serve the pap warm with the tomato relish spooned on top.',
    ],
  },
  {
    id: '4',
    name: 'Beef Mince Curry and Rice',
    image: 'curry',
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    estimatedCost: 110,
    availableIngredients: ['Mince', 'Rice', 'Onions', 'Tomatoes', 'Cooking oil'],
    missingIngredients: ['Curry powder', 'Garlic', 'Ginger'],
    steps: [
      'Brown the mince in a pan with heated oil, breaking it apart.',
      'Add chopped onions and fry until golden and translucent.',
      'Stir in minced garlic, ginger, and curry powder, cooking for 1 minute.',
      'Add chopped tomatoes and a splash of water, simmering for 20 minutes.',
      'Meanwhile, cook rice according to package instructions.',
      'Serve the curry mince over a bed of fluffy rice.',
    ],
  },
  {
    id: '5',
    name: 'Egg Fried Rice',
    image: 'fried-rice',
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    estimatedCost: 45,
    availableIngredients: ['Rice', 'Eggs', 'Onions', 'Cooking oil'],
    missingIngredients: ['Soy sauce', 'Spring onion', 'Peas'],
    steps: [
      'Cook rice in advance and let it cool completely.',
      'Scramble the eggs in a hot wok with a little oil, then set aside.',
      'Sauté chopped onions in oil until soft.',
      'Add the cold rice, breaking up clumps and stir-frying for 5 minutes.',
      'Return the scrambled eggs to the wok and mix through.',
      'Season with soy sauce and garnish with spring onions.',
    ],
  },
  {
    id: '6',
    name: 'Vegetable Soup',
    image: 'soup',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    estimatedCost: 65,
    availableIngredients: ['Tomatoes', 'Potatoes', 'Onions', 'Cooking oil'],
    missingIngredients: ['Carrots', 'Celery', 'Vegetable stock'],
    steps: [
      'Heat oil in a large pot and sauté chopped onions.',
      'Add diced carrots and celery, cooking for 5 minutes.',
      'Stir in chopped tomatoes and peeled potato cubes.',
      'Pour in vegetable stock and bring to a boil.',
      'Reduce heat and simmer for 25 minutes until vegetables are tender.',
      'Season well and serve hot with fresh bread.',
    ],
  },
];

export const expenses: Expense[] = [
  { id: '1', name: 'Pick n Pay — Monthly shop', amount: 1245.5, date: '2026-07-14', category: 'Monthly Shop', items: 23 },
  { id: '2', name: 'Woolworths — Fresh produce', amount: 320.0, date: '2026-07-12', category: 'Fresh Produce', items: 8 },
  { id: '3', name: 'Checkers — Meat and poultry', amount: 456.75, date: '2026-07-10', category: 'Meat and Poultry', items: 5 },
  { id: '4', name: 'Spar — Bread and milk', amount: 89.5, date: '2026-07-08', category: 'Bakery and Dairy', items: 4 },
  { id: '5', name: 'Boxer — Maize meal and rice', amount: 134.25, date: '2026-07-05', category: 'Pantry Staples', items: 6 },
  { id: '6', name: 'Pick n Pay — Vegetables', amount: 78.0, date: '2026-07-03', category: 'Fresh Produce', items: 5 },
];

export const weeklyMealPlan: MealPlanEntry[] = [
  { id: '1', day: 'Monday', recipeId: '3', recipeName: 'Pap and Tomato Relish', mealType: 'Dinner' },
  { id: '2', day: 'Tuesday', recipeId: '5', recipeName: 'Egg Fried Rice', mealType: 'Dinner' },
  { id: '3', day: 'Wednesday', recipeId: '2', recipeName: 'Chicken and Vegetable Stew', mealType: 'Dinner' },
  { id: '4', day: 'Thursday', recipeId: '4', recipeName: 'Beef Mince Curry and Rice', mealType: 'Dinner' },
  { id: '5', day: 'Friday', recipeId: '1', recipeName: 'Creamy Chicken Pasta', mealType: 'Dinner' },
  { id: '6', day: 'Saturday', recipeId: '6', recipeName: 'Vegetable Soup', mealType: 'Dinner' },
  { id: '7', day: 'Sunday', recipeId: '2', recipeName: 'Chicken and Vegetable Stew', mealType: 'Dinner' },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: 'free',
    name: 'RandWise Free',
    price: 0,
    period: 'month',
    description: 'Get started with smart grocery budgeting.',
    features: [
      'One household',
      'One monthly budget',
      'Up to 30 shopping items',
      'Up to 30 pantry items',
      'Three meal suggestions monthly',
      'Basic spending summary',
    ],
    popular: false,
    cta: 'Start Free',
  },
  {
    id: 'family',
    name: 'RandWise Family',
    price: 79,
    period: 'month',
    description: 'Everything a growing household needs.',
    features: [
      'Up to five household members',
      'Unlimited shopping items',
      'Unlimited pantry items',
      'Weekly meal planning',
      '30 AI meal suggestions monthly',
      'Expiry reminders',
      'Low-stock alerts',
      'Detailed reports',
    ],
    popular: true,
    cta: 'Choose Family',
  },
  {
    id: 'plus',
    name: 'RandWise Plus',
    price: 129,
    period: 'month',
    description: 'Premium insights for serious savers.',
    features: [
      'Up to ten household members',
      'Advanced savings insights',
      'Unlimited AI meal suggestions (fair use)',
      'Pantry waste tracking',
      'Downloadable reports',
      'Priority support',
      'Early feature access',
    ],
    popular: false,
    cta: 'Choose Plus',
  },
];

export const householdMembers: HouseholdMember[] = [
  { id: '1', name: 'Lezahn', role: 'Owner', avatar: 'L', color: '#16A34A' },
  { id: '2', name: 'Mariam', role: 'Admin', avatar: 'M', color: '#FBBF24' },
  { id: '3', name: 'Thabo', role: 'Member', avatar: 'T', color: '#3B82F6' },
  { id: '4', name: 'Naledi', role: 'Member', avatar: 'N', color: '#EF4444' },
];

export const notifications: NotificationItem[] = [
  { id: '1', title: 'Milk expiring soon', message: 'Your 2L milk expires in 3 days. Use it before it goes to waste.', time: '2h ago', type: 'warning', read: false },
  { id: '2', title: 'Low stock alert', message: 'Rice is running low. Add it to your shopping list.', time: '5h ago', type: 'info', read: false },
  { id: '3', title: 'Budget milestone', message: 'You have spent 55% of your monthly grocery budget. Keep it up!', time: '1d ago', type: 'success', read: true },
  { id: '4', title: 'Meal suggestion', message: 'Creamy Chicken Pasta is recommended for tonight based on your pantry.', time: '1d ago', type: 'info', read: true },
  { id: '5', title: 'Payment received', message: 'Your RandWise Family subscription is active. Enjoy premium features!', time: '3d ago', type: 'success', read: true },
];

export const comingSoonFeatures = [
  { title: 'Receipt Scanner', description: 'Snap a photo of your till slip and let AI capture every line item automatically.', icon: 'scan' },
  { title: 'Store Price Comparison', description: 'Compare prices across Pick n Pay, Checkers, Woolworths and Spar in real time.', icon: 'compare' },
  { title: 'Budget Goals', description: 'Set weekly and monthly savings goals and track your progress with smart nudges.', icon: 'target' },
  { title: 'Family Challenges', description: 'Turn saving money into a game. Compete with your household to cut food waste.', icon: 'trophy' },
  { title: 'Nutrition Tracking', description: 'See the nutritional breakdown of your weekly meal plan at a glance.', icon: 'heart' },
  { title: 'Voice Shopping', description: 'Add items to your list by speaking. Perfect for hands-free kitchen moments.', icon: 'mic' },
];

export const faqItems = [
  { question: 'How does RandWise track my grocery budget?', answer: 'RandWise lets you set a monthly grocery budget and automatically tracks every purchase you record. Your remaining balance updates in real time so you always know where you stand.' },
  { question: 'Can I share my account with my family?', answer: 'Yes! RandWise Family and Plus plans support multiple household members. Each member can view and update shared shopping lists, pantry items and meal plans.' },
  { question: 'How do expiry reminders work?', answer: 'RandWise monitors your pantry items and sends you a notification when food is about to expire, helping you reduce waste and save money.' },
  { question: 'Is my payment information secure?', answer: 'All payments are processed securely through PayFast, a trusted South African payment gateway. RandWise never stores your card details.' },
  { question: 'Can I cancel my subscription anytime?', answer: 'Absolutely. You can cancel or downgrade your plan at any time from the Billing screen. Your premium features remain active until the end of your billing cycle.' },
  { question: 'Does RandWise work offline?', answer: 'Most features work offline. Your data syncs automatically once you reconnect to the internet.' },
];
