import { makeRecipe, ing } from './helper';

export const airFryerRecipes = [
  makeRecipe({
    id: 'af-chicken-pieces',
    title: 'Air-Fryer Chicken Pieces',
    description: 'Crispy, juicy chicken pieces cooked in the air fryer with a simple seasoning. No deep frying needed.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Family Dinner', 'Air-Fryer', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 95,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Chicken portions', 1, 'kg', 90),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Paprika', 1, 'tsp', 2, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Peri-peri', 1, 'tsp', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Chicken portions', substitute: 'Chicken wings or drumsticks' },
      { ingredient: 'Paprika', substitute: 'Curry powder or mixed herbs' },
    ],
    instructions: [
      'Pat the chicken pieces dry with paper towels. Removing surface moisture helps the skin crisp up in the air fryer.',
      'Crush the garlic. In a bowl, combine the oil, crushed garlic, salt, pepper, paprika and peri-peri if using. Add the chicken pieces and toss until evenly coated.',
      'Preheat the air fryer to 200°C for 3 minutes.',
      'Arrange the chicken pieces in the air fryer basket in a single layer, leaving space between each piece for air to circulate. Do not overcrowd — cook in two batches if needed.',
      'Cook at 200°C for 20-25 minutes. Flip the pieces halfway through cooking at the 12-minute mark for even browning.',
      'The chicken is cooked when the internal temperature reaches 75°C, the juices run clear with no pink, and the skin is golden and crispy.',
      'Remove from the air fryer and rest for 3 minutes before serving. Serve with a side salad or chips.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free', 'Low-Carb'],
    allergenTags: [],
    thumbnail: 'af-chicken',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the air fryer at 180°C for 5 minutes to restore crispiness.',
    leftoverSuggestions: 'Shred leftover chicken for wraps, sandwiches, or add to a salad. The crispy skin is delicious crumbled over soup.',
  }),

  makeRecipe({
    id: 'af-potato-wedges',
    title: 'Air-Fryer Potato Wedges',
    description: 'Crispy potato wedges with a fluffy inside, cooked in the air fryer with minimal oil.',
    mealCategory: 'Snack',
    recipeCategories: ['Quick Weekday', 'Budget', 'Air-Fryer', 'No-Oven', 'Snack', 'Vegetarian'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 25,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Potatoes', 4, 'whole', 12),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Paprika', 1, 'tsp', 2, { isStaple: true }),
      ing('Garlic', 1, 'clove', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Peri-peri', 1, 'tsp', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Potatoes', substitute: 'Sweet potatoes' },
    ],
    instructions: [
      'Wash the potatoes thoroughly. You can leave the skin on for extra texture. Cut each potato into 6-8 wedges of equal size so they cook evenly.',
      'Place the wedges in a bowl. Add the oil, salt, paprika, crushed garlic and peri-peri if using. Toss until every wedge is evenly coated.',
      'Preheat the air fryer to 200°C for 3 minutes.',
      'Arrange the wedges in the air fryer basket in a single layer. Do not overlap or they will steam instead of crisping. Cook in batches if needed.',
      'Cook at 200°C for 18-20 minutes. Shake the basket halfway through at the 10-minute mark to ensure even cooking.',
      'The wedges are ready when they are golden brown and crispy on the outside, and you can easily pierce the centre with a fork.',
      'Remove from the air fryer, sprinkle with extra salt if desired, and serve hot with tomato sauce or chutney.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free', 'Gluten-Free'],
    allergenTags: [],
    thumbnail: 'af-wedges',
    storageInstructions: 'Best eaten immediately. If storing, keep in the fridge for up to 1 day and reheat in the air fryer at 200°C for 4 minutes to restore crispiness.',
    leftoverSuggestions: 'Use leftover wedges as a topping for a breakfast hash with eggs, or serve alongside a salad for a light lunch.',
  }),

  makeRecipe({
    id: 'af-meatballs',
    title: 'Air-Fryer Meatballs',
    description: 'Juicy homemade meatballs cooked in the air fryer. Serve with pasta or in a sauce.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Family Dinner', 'Air-Fryer', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 75,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Mince', 500, 'g', 55),
      ing('Onions', 0.5, 'whole', 2),
      ing('Eggs', 1, 'whole', 4),
      ing('Breadcrumbs', 0.5, 'cup', 3, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Breadcrumbs', substitute: '2 tbsp flour or crushed crackers' },
      { ingredient: 'Beef mince', substitute: 'Chicken mince or pork mince' },
    ],
    instructions: [
      'Finely dice the onion. Crush the garlic. If using cheese, grate it finely.',
      'In a large bowl, combine the mince, diced onion, garlic, egg, breadcrumbs, mixed herbs, salt and pepper. If using cheese, add it now. Mix with your hands until well combined.',
      'Shape the mixture into 16-20 meatballs about 3cm in diameter. Roll them firmly so they hold together.',
      'Brush or spray the meatballs lightly with cooking oil. This helps them brown in the air fryer.',
      'Preheat the air fryer to 190°C for 3 minutes. Arrange the meatballs in the basket in a single layer with space between each.',
      'Cook at 190°C for 10-12 minutes. Shake the basket gently at the 6-minute mark to rotate the meatballs.',
      'The meatballs are cooked when they are golden brown on the outside and reach an internal temperature of 75°C with no pink inside. Serve hot with pasta and tomato sauce, or on their own with a dip.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: ['Eggs', 'Gluten'],
    thumbnail: 'af-meatballs',
    storageInstructions: 'Store in the fridge for up to 3 days. Reheat in the air fryer at 180°C for 4 minutes. Can be frozen for up to 1 month.',
    leftoverSuggestions: 'Place leftover meatballs in a bread roll with cheese and sauce for a meatball sub. Alternatively, add to a soup or stew.',
  }),

  makeRecipe({
    id: 'af-fish',
    title: 'Air-Fryer Fish',
    description: 'Lightly breaded fish fillets cooked crispy in the air fryer. Much healthier than deep-fried fish.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Air-Fryer', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 12,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 70,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Fish', 4, 'fillets', 55),
      ing('Flour', 0.5, 'cup', 3, { isStaple: true }),
      ing('Eggs', 1, 'whole', 4),
      ing('Breadcrumbs', 1, 'cup', 5, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Lemon', 0.5, 'whole', 4),
    ],
    optionalIngredients: [
      ing('Paprika', 1, 'tsp', 2, { isOptional: true, isStaple: true }),
    ],
    substitutes: [
      { ingredient: 'Breadcrumbs', substitute: 'Crushed cornflakes or maize meal' },
      { ingredient: 'Fish fillets', substitute: 'Fish fingers or prawns' },
    ],
    instructions: [
      'Pat the fish fillets dry with paper towels. Season both sides with salt and pepper.',
      'Set up three shallow dishes: one with flour, one with the beaten egg, and one with breadcrumbs mixed with paprika if using.',
      'Dredge each fish fillet in flour, shaking off excess. Dip into the beaten egg, coating completely. Then press into the breadcrumbs, coating both sides firmly.',
      'Lightly spray or brush the breaded fillets with cooking oil on both sides. This helps them crisp up in the air fryer.',
      'Preheat the air fryer to 200°C for 3 minutes. Arrange the fillets in the basket in a single layer.',
      'Cook at 200°C for 10-12 minutes. Carefully flip the fillets at the 6-minute mark using a spatula.',
      'The fish is cooked when it is golden and crispy on the outside and flakes easily with a fork. The flesh should be opaque white throughout. Serve hot with lemon wedges and chips or a salad.',
    ],
    dietaryTags: ['Pescatarian', 'High-Protein'],
    allergenTags: ['Fish', 'Eggs', 'Gluten'],
    thumbnail: 'af-fish',
    storageInstructions: 'Best eaten immediately. If storing, keep in the fridge for up to 1 day and reheat in the air fryer at 180°C for 4 minutes.',
    leftoverSuggestions: 'Flake leftover fish into a wrap with mayonnaise and lettuce, or use in a fish taco with salsa.',
  }),

  makeRecipe({
    id: 'af-chicken-wings',
    title: 'Air-Fryer Chicken Wings',
    description: 'Crispy chicken wings tossed in a peri-peri marinade. Perfect as a snack or party food.',
    mealCategory: 'Snack',
    recipeCategories: ['Air-Fryer', 'No-Oven', 'Snack'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 65,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Chicken wings', 1, 'kg', 55),
      ing('Peri-peri', 2, 'tbsp', 8),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Lemon', 0.5, 'whole', 4, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Peri-peri', substitute: 'BBQ sauce or sweet chilli sauce' },
    ],
    instructions: [
      'Pat the chicken wings dry with paper towels. Crush the garlic.',
      'In a bowl, combine the peri-peri, oil, crushed garlic, salt and pepper. Add the wings and toss until evenly coated. For best flavour, marinate for 30 minutes.',
      'Preheat the air fryer to 200°C for 3 minutes.',
      'Arrange the wings in the air fryer basket in a single layer. Do not overcrowd — cook in batches if needed.',
      'Cook at 200°C for 18-20 minutes. Shake the basket at the 10-minute mark to flip the wings.',
      'The wings are cooked when the skin is crispy and golden, and the internal temperature reaches 75°C with clear juices and no pink near the bone.',
      'Remove from the air fryer and toss in any remaining marinade. Squeeze lemon over if using and serve hot.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free', 'Low-Carb'],
    allergenTags: [],
    thumbnail: 'af-wings',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the air fryer at 190°C for 5 minutes to restore crispiness.',
    leftoverSuggestions: 'Shred leftover wing meat and use in a chicken mayo sandwich or add to a salad.',
  }),

  makeRecipe({
    id: 'af-sausage-rolls',
    title: 'Air-Fryer Sausage Rolls',
    description: 'Homemade sausage rolls wrapped in pastry and cooked crispy in the air fryer.',
    mealCategory: 'Snack',
    recipeCategories: ['Air-Fryer', 'No-Oven', 'Snack', 'Lunchbox'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 15,
    servings: 6,
    difficulty: 'Medium',
    estimatedTotalCost: 70,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Sausages', 6, 'whole', 55),
      ing('Flour', 2, 'cups', 5, { isStaple: true }),
      ing('Butter', 100, 'g', 8, { isStaple: true }),
      ing('Eggs', 1, 'whole', 4),
      ing('Salt', 0.5, 'tsp', 1, { isStaple: true }),
      ing('Cold water', 3, 'tbsp', 0),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Sausages', substitute: 'Boerewors, casings removed' },
      { ingredient: 'Butter', substitute: 'Margarine or baking block' },
    ],
    instructions: [
      'Make the pastry: rub the butter into the flour and salt until the mixture resembles breadcrumbs. Add cold water gradually and mix until a dough forms. Wrap in cling film and chill for 15 minutes.',
      'Remove the sausage meat from the casings. If using cheese, grate it. Beat the egg in a small bowl for egg wash.',
      'Roll the pastry out on a floured surface into a rectangle about 3mm thick. Cut into 6 long strips.',
      'Place a line of sausage meat (and cheese if using) along the centre of each pastry strip. Brush one edge with egg wash.',
      'Fold the pastry over the filling and seal the edge. Cut each roll into 3-4 pieces. Place seam-side down. Brush the tops with egg wash.',
      'Preheat the air fryer to 180°C for 3 minutes. Arrange the sausage rolls in the basket with space between them.',
      'Cook at 180°C for 12-15 minutes until the pastry is golden brown and the sausage meat is cooked through (no pink inside). Serve hot.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Gluten', 'Dairy', 'Eggs'],
    thumbnail: 'af-sausage-rolls',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the air fryer at 170°C for 4 minutes. Can be frozen uncooked for up to 1 month.',
    leftoverSuggestions: 'Serve cold leftover sausage rolls with chutney as a snack. Alternatively, chop and add to a lunchbox salad.',
  }),

  makeRecipe({
    id: 'af-veggie-fritters',
    title: 'Air-Fryer Vegetable Fritters',
    description: 'Crispy vegetable fritters made with carrots, onions and corn. A healthy air-fryer snack.',
    mealCategory: 'Snack',
    recipeCategories: ['Quick Weekday', 'Budget', 'Air-Fryer', 'No-Oven', 'Vegetarian', 'Snack'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 35,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Carrots', 2, 'whole', 6),
      ing('Onions', 1, 'whole', 3),
      ing('Sweet corn', 1, 'can', 12),
      ing('Eggs', 2, 'whole', 8),
      ing('Flour', 0.5, 'cup', 3, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Sweet corn', substitute: 'Peas or grated zucchini' },
      { ingredient: 'Flour', substitute: 'Maize meal' },
    ],
    instructions: [
      'Grate the carrots finely. Finely dice the onion. Drain the sweet corn.',
      'In a bowl, combine the grated carrot, diced onion, drained corn, eggs, flour, salt and pepper. If using cheese, grate and add now. Mix until well combined.',
      'Shape the mixture into 8-10 flat fritters, pressing firmly so they hold together.',
      'Lightly brush or spray the fritters with oil on both sides.',
      'Preheat the air fryer to 190°C for 3 minutes. Arrange the fritters in the basket in a single layer.',
      'Cook at 190°C for 10-12 minutes. Carefully flip the fritters at the 6-minute mark.',
      'The fritters are ready when they are golden brown and crispy on both sides. Serve hot with chutney or a dipping sauce.',
    ],
    dietaryTags: ['Vegetarian'],
    allergenTags: ['Eggs', 'Gluten'],
    thumbnail: 'af-fritters',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the air fryer at 180°C for 3 minutes.',
    leftoverSuggestions: 'Serve leftover fritters in a wrap with lettuce and mayonnaise, or crumble over a salad for crunch.',
  }),

  makeRecipe({
    id: 'af-chicken-drumsticks',
    title: 'Air-Fryer Chicken Drumsticks',
    description: 'Seasoned drumsticks with crispy skin, cooked to perfection in the air fryer.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'Air-Fryer', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 65,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Chicken drumsticks', 8, 'whole', 55),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Paprika', 1, 'tsp', 2, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Honey', 1, 'tbsp', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Chicken drumsticks', substitute: 'Chicken thighs or wings' },
    ],
    instructions: [
      'Pat the drumsticks dry with paper towels. Crush the garlic.',
      'In a bowl, combine the oil, garlic, salt, pepper, paprika and mixed herbs. Add the drumsticks and toss until evenly coated.',
      'Preheat the air fryer to 200°C for 3 minutes.',
      'Arrange the drumsticks in the air fryer basket in a single layer with space between them. Cook in batches if needed.',
      'Cook at 200°C for 22-25 minutes. Turn the drumsticks at the 12-minute mark for even browning.',
      'If using honey, brush it on during the last 3 minutes of cooking for a sticky glaze.',
      'The drumsticks are cooked when the internal temperature reaches 75°C, the juices run clear, and the skin is golden and crispy. Rest for 3 minutes before serving.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free', 'Low-Carb'],
    allergenTags: [],
    thumbnail: 'af-drumsticks',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the air fryer at 190°C for 5 minutes.',
    leftoverSuggestions: 'Remove the meat from the bones and use in sandwiches, wraps, or add to a chicken salad.',
  }),

  makeRecipe({
    id: 'af-sweet-potato-fries',
    title: 'Air-Fryer Sweet Potato Fries',
    description: 'Crispy sweet potato fries with a hint of paprika. A healthier alternative to regular chips.',
    mealCategory: 'Snack',
    recipeCategories: ['Quick Weekday', 'Air-Fryer', 'No-Oven', 'Vegetarian', 'Snack'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 30,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Sweet potato', 2, 'whole', 15),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Paprika', 1, 'tsp', 2, { isStaple: true }),
      ing('Pepper', 0.5, 'tsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cinnamon', 0.5, 'tsp', 2, { isOptional: true, isStaple: true }),
    ],
    substitutes: [
      { ingredient: 'Sweet potato', substitute: 'Butternut, cut into fries' },
    ],
    instructions: [
      'Peel the sweet potatoes and cut into 1cm thick fries. Try to keep them uniform for even cooking.',
      'Place the fries in a bowl. Add the oil, salt, paprika, pepper and cinnamon if using. Toss until evenly coated.',
      'Preheat the air fryer to 200°C for 3 minutes.',
      'Arrange the fries in the air fryer basket in a single layer. Do not overlap. Cook in batches if needed.',
      'Cook at 200°C for 13-15 minutes. Shake the basket every 5 minutes for even cooking.',
      'The fries are ready when they are crispy on the outside and tender on the inside. You should be able to pierce them easily with a fork.',
      'Remove from the air fryer, sprinkle with extra salt if desired, and serve hot.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free', 'Gluten-Free'],
    allergenTags: [],
    thumbnail: 'af-sweet-fries',
    storageInstructions: 'Best eaten immediately. Sweet potato fries do not reheat well — they lose their crispiness.',
    leftoverSuggestions: 'Add cold leftover fries to a breakfast hash, or blend into a sweet potato soup.',
  }),

  makeRecipe({
    id: 'af-chicken-strips',
    title: 'Air-Fryer Chicken Strips',
    description: 'Crispy breaded chicken strips, perfect for kids. Serve with a dipping sauce.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Family Dinner', 'Air-Fryer', 'No-Oven', 'Lunchbox', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 70,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Chicken breast', 500, 'g', 65),
      ing('Flour', 0.5, 'cup', 3, { isStaple: true }),
      ing('Eggs', 1, 'whole', 4),
      ing('Breadcrumbs', 1, 'cup', 5, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Paprika', 1, 'tsp', 2, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Breadcrumbs', substitute: 'Crushed cornflakes or crackers' },
    ],
    instructions: [
      'Cut the chicken breast into 2cm wide strips. Season with salt and pepper.',
      'Set up three dishes: flour with paprika, beaten egg, and breadcrumbs (with grated cheese if using).',
      'Dredge each strip in flour, then dip in egg, then press firmly into breadcrumbs. Place on a plate.',
      'Lightly spray or brush the strips with oil on both sides.',
      'Preheat the air fryer to 200°C for 3 minutes. Arrange the strips in the basket in a single layer.',
      'Cook at 200°C for 10-12 minutes. Flip the strips at the 6-minute mark.',
      'The strips are cooked when they are golden brown and crispy, and the chicken is cooked through (no pink inside, internal temp 75°C). Serve hot with a dipping sauce.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Eggs', 'Gluten', 'Dairy'],
    thumbnail: 'af-strips',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the air fryer at 190°C for 4 minutes to restore crispiness.',
    leftoverSuggestions: 'Use leftover strips in a wrap with lettuce and mayonnaise, or chop and add to a Caesar salad.',
  }),

  makeRecipe({
    id: 'af-mushrooms',
    title: 'Air-Fryer Garlic Mushrooms',
    description: 'Whole mushrooms roasted in the air fryer with garlic and herbs. A quick side dish.',
    mealCategory: 'Snack',
    recipeCategories: ['Quick Weekday', 'Air-Fryer', 'No-Oven', 'Vegetarian', 'Snack'],
    cuisineType: 'South African',
    prepTime: 5,
    cookTime: 10,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 40,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Mushrooms', 300, 'g', 25),
      ing('Butter', 2, 'tbsp', 4, { isStaple: true }),
      ing('Garlic', 4, 'cloves', 5, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Salt', 0.5, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 0.5, 'tsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Butter', substitute: 'Olive oil or cooking oil' },
    ],
    instructions: [
      'Wipe the mushrooms clean with a damp cloth. Do not soak them in water as they will become soggy.',
      'Crush the garlic. Melt the butter in a small bowl (microwave for 20 seconds).',
      'In a bowl, toss the mushrooms with the melted butter, crushed garlic, mixed herbs, salt and pepper until evenly coated.',
      'Preheat the air fryer to 190°C for 3 minutes.',
      'Arrange the mushrooms in the air fryer basket in a single layer, cap-side up.',
      'Cook at 190°C for 8-10 minutes. Shake the basket gently at the 5-minute mark.',
      'The mushrooms are ready when they are tender, slightly browned and have released their juices. If using cheese, sprinkle it on during the last 2 minutes. Serve hot.',
    ],
    dietaryTags: ['Vegetarian', 'Gluten-Free', 'Low-Carb'],
    allergenTags: ['Dairy'],
    thumbnail: 'af-mushrooms',
    storageInstructions: 'Best eaten immediately. If storing, keep in the fridge for up to 1 day and reheat in the air fryer at 180°C for 3 minutes.',
    leftoverSuggestions: 'Slice leftover mushrooms and add to an omelette, pasta, or serve on toast with a poached egg.',
  }),

  makeRecipe({
    id: 'af-pork-chops',
    title: 'Air-Fryer Pork Chops',
    description: 'Juicy pork chops with a crispy herb crust, cooked quickly in the air fryer.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Air-Fryer', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 80,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Pork chops', 4, 'whole', 65),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Paprika', 1, 'tsp', 2, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Honey', 1, 'tbsp', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Pork chops', substitute: 'Lamb chops or chicken breast' },
    ],
    instructions: [
      'Pat the pork chops dry with paper towels. Crush the garlic.',
      'In a small bowl, mix the oil, garlic, paprika, mixed herbs, salt and pepper. Rub this mixture over both sides of each pork chop.',
      'Preheat the air fryer to 190°C for 3 minutes.',
      'Arrange the pork chops in the air fryer basket in a single layer. Do not overlap.',
      'Cook at 190°C for 12-15 minutes. Flip the chops at the 7-minute mark.',
      'If using honey, brush it on during the last 2 minutes for a sticky glaze.',
      'The pork is cooked when the internal temperature reaches 71°C and the juices run clear with no pink in the centre. Rest for 3 minutes before serving.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free', 'Low-Carb'],
    allergenTags: [],
    thumbnail: 'af-pork-chops',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the air fryer at 170°C for 4 minutes. Do not overcook when reheating as pork dries out.',
    leftoverSuggestions: 'Dice leftover pork and add to a stir-fry with rice and vegetables, or use in a sandwich with apple chutney.',
  }),

  makeRecipe({
    id: 'af-stuffed-peppers',
    title: 'Air-Fryer Stuffed Peppers',
    description: 'Bell peppers stuffed with a savoury rice and vegetable filling. A complete meal in one.',
    mealCategory: 'Dinner',
    recipeCategories: ['Air-Fryer', 'No-Oven', 'Vegetarian', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    difficulty: 'Medium',
    estimatedTotalCost: 65,
    equipment: ['Air Fryer', 'Stove', 'Pot'],
    ingredients: [
      ing('Green pepper', 4, 'whole', 32),
      ing('Rice', 1, 'cup', 8),
      ing('Onions', 1, 'whole', 3),
      ing('Tomatoes', 2, 'whole', 6),
      ing('Sweet corn', 1, 'can', 12),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 2, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
      ing('Mince', 200, 'g', 22, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Green pepper', substitute: 'Any large bell pepper' },
    ],
    instructions: [
      'Cook the rice: bring 2 cups of water to a boil, add rice and a pinch of salt, cover and simmer for 18 minutes. Fluff with a fork.',
      'While the rice cooks, cut the tops off the peppers and scoop out the seeds. Finely dice the onion and tomatoes. Drain the corn. Crush the garlic.',
      'Heat 1 tablespoon of oil in a pan over medium heat. Fry the onion and garlic for 3 minutes. If using mince, add and brown for 5 minutes.',
      'Add the diced tomatoes, corn, mixed herbs, salt and pepper. Cook for 5 minutes. Remove from heat and stir in the cooked rice.',
      'Stuff each pepper generously with the rice mixture, pressing down firmly. If using cheese, sprinkle on top.',
      'Preheat the air fryer to 180°C for 3 minutes. Place the stuffed peppers in the basket standing upright.',
      'Cook at 180°C for 15-20 minutes until the peppers are tender and the filling is heated through. The peppers are ready when they have softened and slightly blistered. Serve hot.',
    ],
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    allergenTags: ['Dairy'],
    thumbnail: 'af-peppers',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the air fryer at 170°C for 5 minutes.',
    leftoverSuggestions: 'Scoop out the filling and use as a rice salad base, or add to a wrap with lettuce.',
  }),

  makeRecipe({
    id: 'af-corn-on-cob',
    title: 'Air-Fryer Corn on the Cob',
    description: 'Sweet corn on the cob with a butter and herb coating. A quick and easy side dish.',
    mealCategory: 'Snack',
    recipeCategories: ['Quick Weekday', 'Air-Fryer', 'No-Oven', 'Vegetarian', 'Snack'],
    cuisineType: 'South African',
    prepTime: 5,
    cookTime: 12,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 25,
    equipment: ['Air Fryer'],
    ingredients: [
      ing('Corn on the cob', 4, 'whole', 20),
      ing('Butter', 2, 'tbsp', 4, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 0.5, 'tsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Peri-peri', 1, 'tsp', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Butter', substitute: 'Cooking oil or margarine' },
    ],
    instructions: [
      'Remove the husks and silk from the corn. Cut each cob in half if needed to fit the air fryer.',
      'Melt the butter in a small bowl (microwave for 20 seconds). Add salt, pepper and peri-peri if using.',
      'Brush the butter mixture over each corn cob, coating evenly.',
      'Preheat the air fryer to 200°C for 3 minutes.',
      'Arrange the corn cobs in the air fryer basket in a single layer.',
      'Cook at 200°C for 10-12 minutes. Turn the cobs at the 6-minute mark for even cooking.',
      'The corn is ready when it is lightly charred and tender when pierced with a fork. Brush with any remaining butter and serve hot.',
    ],
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    allergenTags: ['Dairy'],
    thumbnail: 'af-corn',
    storageInstructions: 'Best eaten immediately. If storing, keep in the fridge for up to 1 day and reheat in the air fryer at 180°C for 3 minutes.',
    leftoverSuggestions: 'Cut the kernels off the cob and add to a salad, salsa, or mix into fried rice.',
  }),

  makeRecipe({
    id: 'af-samoosas',
    title: 'Air-Fryer Mince Samoosas',
    description: 'Crispy triangular pastries filled with spiced mince. A South African favourite made healthier in the air fryer.',
    mealCategory: 'Snack',
    recipeCategories: ['Air-Fryer', 'No-Oven', 'Snack', 'Lunchbox'],
    cuisineType: 'South African',
    prepTime: 30,
    cookTime: 12,
    servings: 6,
    difficulty: 'Hard',
    estimatedTotalCost: 65,
    equipment: ['Air Fryer', 'Stove', 'Pan'],
    ingredients: [
      ing('Mince', 300, 'g', 33),
      ing('Onions', 1, 'whole', 3),
      ing('Flour', 2, 'cups', 5, { isStaple: true }),
      ing('Curry powder', 2, 'tsp', 3, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Peas', 0.5, 'cup', 5),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 0.5, 'tsp', 1, { isStaple: true }),
      ing('Water', 0.5, 'cup', 0),
    ],
    optionalIngredients: [
      ing('Coriander', 1, 'handful', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Mince', substitute: 'Potato and pea filling for vegetarian samoosas' },
    ],
    instructions: [
      'Make the filling: finely dice the onion and crush the garlic. Heat oil in a pan over medium-high heat. Brown the mince for 5 minutes until no pink remains.',
      'Add the onion, garlic and curry powder. Fry for 3 minutes. Add the peas, salt, pepper and 1/4 cup water. Simmer for 8 minutes until the mixture is dry. Let it cool completely.',
      'Make the pastry: mix flour and salt. Add 1 tablespoon of oil and enough water to form a stiff dough. Knead for 5 minutes. Rest for 15 minutes.',
      'Roll the dough thin and cut into rectangles about 10cm x 5cm. Place a spoonful of filling at one end. Fold into triangles by folding the corner over diagonally repeatedly.',
      'Seal the final edge with a paste of flour and water. Lightly brush with oil.',
      'Preheat the air fryer to 180°C for 3 minutes. Arrange the samoosas in the basket in a single layer.',
      'Cook at 180°C for 10-12 minutes until golden brown and crispy. Turn at the 6-minute mark. Serve hot with chutney.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Gluten'],
    thumbnail: 'af-samoosas',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the air fryer at 170°C for 4 minutes. Uncooked samoosas can be frozen for up to 1 month.',
    leftoverSuggestions: 'Crumble leftover samoosas over a salad, or serve with a soup as a crunchy side.',
  }),
];
