import { makeRecipe, ing } from './helper';

export const breakfastRecipes = [
  makeRecipe({
    id: 'bf-french-toast',
    title: 'French Toast',
    description: 'Golden, crispy French toast made with eggs and milk. A quick and filling breakfast.',
    mealCategory: 'Breakfast',
    recipeCategories: ['Breakfast', 'Quick Weekday', 'Budget', 'Vegetarian', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 5,
    cookTime: 10,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 30,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Bread', 8, 'slices', 16),
      ing('Eggs', 4, 'whole', 16),
      ing('Milk', 0.5, 'cup', 5),
      ing('Sugar', 1, 'tbsp', 2, { isStaple: true }),
      ing('Cinnamon', 0.5, 'tsp', 2, { isStaple: true }),
      ing('Butter', 2, 'tbsp', 4, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Banana', 1, 'whole', 4, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Milk', substitute: 'Water or rooibos tea' },
      { ingredient: 'Butter', substitute: 'Cooking oil' },
    ],
    instructions: [
      'Crack the eggs into a wide, shallow bowl. Add the milk, sugar and cinnamon. Whisk until well combined.',
      'Heat a pan over medium heat and melt 1 tablespoon of butter.',
      'Dip each slice of bread into the egg mixture for 5 seconds per side, allowing it to soak up the mixture without becoming soggy.',
      'Place the soaked bread in the pan. Cook for 2-3 minutes per side until golden brown.',
      'Add more butter to the pan between batches as needed.',
      'The French toast is ready when both sides are golden and crispy. Serve hot with a sprinkle of cinnamon sugar, or top with sliced banana if using.',
    ],
    dietaryTags: ['Vegetarian'],
    allergenTags: ['Eggs', 'Dairy', 'Gluten'],
    thumbnail: 'bf-french-toast',
    storageInstructions: 'Best eaten immediately. If storing, keep in the fridge for up to 1 day and reheat in a toaster or pan.',
    leftoverSuggestions: 'Use leftover French toast as a base for a bread pudding, or serve with ice cream as a dessert.',
  }),

  makeRecipe({
    id: 'bf-oats',
    title: 'Oats with Banana and Honey',
    description: 'Warm, filling oats topped with banana and a drizzle of honey. A healthy breakfast.',
    mealCategory: 'Breakfast',
    recipeCategories: ['Breakfast', 'Quick Weekday', 'Budget', 'Healthy', 'Vegetarian', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 2,
    cookTime: 10,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 25,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Oats', 2, 'cups', 12),
      ing('Milk', 2, 'cups', 10),
      ing('Banana', 2, 'whole', 8),
      ing('Honey', 2, 'tbsp', 5),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cinnamon', 0.5, 'tsp', 2, { isOptional: true, isStaple: true }),
    ],
    substitutes: [
      { ingredient: 'Milk', substitute: 'Water' },
      { ingredient: 'Honey', substitute: 'Sugar or maple syrup' },
    ],
    instructions: [
      'Combine the oats, milk and a pinch of salt in a pot. Stir well.',
      'Place over medium heat and bring to a gentle simmer, stirring frequently to prevent the oats from sticking to the bottom.',
      'Reduce the heat to low and cook for 5-7 minutes, stirring occasionally, until the oats are soft and creamy.',
      'Remove from heat. Slice the bananas.',
      'Spoon the oats into bowls. Top with sliced banana, a drizzle of honey and a sprinkle of cinnamon if using.',
      'Serve immediately while warm.',
    ],
    dietaryTags: ['Vegetarian'],
    allergenTags: ['Dairy'],
    thumbnail: 'bf-oats',
    storageInstructions: 'Store leftover oats in the fridge for up to 1 day. Reheat with a splash of milk on the stove or microwave.',
    leftoverSuggestions: 'Use leftover oats to make oat pancakes by adding an egg and flour, then frying in a pan.',
  }),

  makeRecipe({
    id: 'bf-eggs-on-toast',
    title: 'Scrambled Eggs on Toast',
    description: 'Fluffy scrambled eggs on toasted bread. A classic, protein-rich breakfast.',
    mealCategory: 'Breakfast',
    recipeCategories: ['Breakfast', 'Quick Weekday', 'Budget', 'High-Protein', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 5,
    cookTime: 8,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 35,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Eggs', 6, 'whole', 24),
      ing('Bread', 4, 'slices', 8),
      ing('Butter', 2, 'tbsp', 4, { isStaple: true }),
      ing('Milk', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Butter', substitute: 'Cooking oil or margarine' },
    ],
    instructions: [
      'Crack the eggs into a bowl. Add the milk, salt and pepper. Whisk until the mixture is uniform and slightly frothy.',
      'Toast the bread slices and set aside.',
      'Melt the butter in a pan over low-medium heat. Pour in the egg mixture.',
      'Let the eggs sit for 10 seconds, then gently push the cooked edges towards the centre with a spatula. Tilt the pan to let the uncooked egg flow to the edges.',
      'Continue gently folding the eggs for 3-4 minutes until they form soft, glossy curds. Do not overcook — they will continue to cook from residual heat.',
      'If using cheese, sprinkle it over the eggs just before they finish cooking. Spoon the scrambled eggs onto the toasted bread and serve immediately.',
    ],
    dietaryTags: ['High-Protein', 'Vegetarian'],
    allergenTags: ['Eggs', 'Dairy', 'Gluten'],
    thumbnail: 'bf-eggs-toast',
    storageInstructions: 'Best eaten immediately. Scrambled eggs do not reheat well.',
    leftoverSuggestions: 'Use leftover scrambled eggs in a breakfast wrap with cheese and tomato, or mash and spread on toast.',
  }),

  makeRecipe({
    id: 'bf-meal-pap',
    title: 'Mealie Meal Pap with Milk and Sugar',
    description: 'Soft maize meal pap served with milk and sugar. A comforting, traditional South African breakfast.',
    mealCategory: 'Breakfast',
    recipeCategories: ['Breakfast', 'Budget', 'Quick Weekday', 'Vegetarian', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 5,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 20,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Maize meal', 2, 'cups', 8),
      ing('Milk', 2, 'cups', 10),
      ing('Sugar', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Banana', 1, 'whole', 4, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Milk', substitute: 'Water with extra sugar' },
    ],
    instructions: [
      'Bring 3 cups of water to a boil in a pot. Add a pinch of salt.',
      'Gradually whisk in the maize meal, stirring constantly to prevent lumps from forming.',
      'Reduce the heat to low. Cover and cook for 10-12 minutes, stirring every 2-3 minutes to prevent sticking and burning.',
      'The pap is ready when it is smooth, thick and pulls away from the sides of the pot.',
      'Spoon the pap into bowls. Pour warm milk over the top and sprinkle with sugar.',
      'If using banana, slice and add on top. Serve warm.',
    ],
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    allergenTags: ['Dairy'],
    thumbnail: 'bf-meal-pap',
    storageInstructions: 'Store leftover pap in the fridge for up to 2 days. Reheat with a little water or milk on the stove.',
    leftoverSuggestions: 'Leftover pap can be sliced and fried in butter for a crispy breakfast treat, or served with savory relish instead of milk and sugar.',
  }),

  makeRecipe({
    id: 'bf-breakfast-burrito',
    title: 'Breakfast Burrito',
    description: 'A flour tortilla filled with scrambled eggs, cheese and tomato. A filling breakfast on the go.',
    mealCategory: 'Breakfast',
    recipeCategories: ['Breakfast', 'Quick Weekday', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 55,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Eggs', 6, 'whole', 24),
      ing('Tortilla wraps', 4, 'whole', 20),
      ing('Cheese', 100, 'g', 15),
      ing('Tomatoes', 1, 'whole', 3),
      ing('Onions', 0.5, 'whole', 2),
      ing('Butter', 1, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Bacon', 100, 'g', 20, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Tortilla wraps', substitute: 'Bread for a breakfast sandwich' },
    ],
    instructions: [
      'Dice the tomato and onion. Grate the cheese.',
      'Melt butter in a pan over medium heat. Add the onion and fry for 2 minutes until soft.',
      'Crack the eggs into a bowl, add salt and pepper, and whisk. Pour into the pan with the onion.',
      'Gently scramble the eggs for 3-4 minutes until just set but still soft. Remove from heat.',
      'Warm the tortilla wraps in a dry pan for 10 seconds per side.',
      'Place each wrap on a plate. Spoon a quarter of the scrambled eggs onto the centre. Top with grated cheese and diced tomato. If using bacon, add crispy bacon strips.',
      'Fold the sides of the wrap over the filling, then roll up tightly from the bottom. Serve warm.',
    ],
    dietaryTags: ['High-Protein', 'Vegetarian'],
    allergenTags: ['Eggs', 'Dairy', 'Gluten'],
    thumbnail: 'bf-burrito',
    storageInstructions: 'Wrap tightly and store in the fridge for up to 1 day. Reheat in a pan over low heat or microwave for 30 seconds.',
    leftoverSuggestions: 'Slice leftover burritos and serve with a side salad, or unwrap and scramble the filling with rice.',
  }),

  makeRecipe({
    id: 'bf-egg-muffins',
    title: 'Egg and Vegetable Muffins',
    description: 'Mini egg muffins with vegetables, baked in a pan. Perfect for meal prep and lunchboxes.',
    mealCategory: 'Breakfast',
    recipeCategories: ['Breakfast', 'Quick Weekday', 'Budget', 'High-Protein', 'Vegetarian', 'Lunchbox', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 40,
    equipment: ['Stove', 'Pan', 'Muffin Tin'],
    ingredients: [
      ing('Eggs', 6, 'whole', 24),
      ing('Sweet corn', 0.5, 'can', 6),
      ing('Carrots', 1, 'whole', 3),
      ing('Cheese', 50, 'g', 10),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
      ing('Cooking oil', 1, 'tsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Bacon', 50, 'g', 10, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Sweet corn', substitute: 'Diced ham or mushrooms' },
    ],
    instructions: [
      'Grate the carrot and cheese. Drain the sweet corn. If using bacon, dice and fry until crispy.',
      'Crack the eggs into a bowl. Add the salt, pepper, grated carrot, corn, cheese and cooked bacon if using. Whisk until combined.',
      'Grease a muffin tin with cooking oil.',
      'Pour the egg mixture into the muffin tin, filling each cup about 3/4 full.',
      'Place the muffin tin in a large pan with 1cm of water. Cover and steam over medium-low heat for 12-15 minutes.',
      'The egg muffins are ready when they are set and a toothpick inserted comes out clean. Alternatively, bake in the oven at 180°C for 15 minutes.',
      'Remove from the tin and serve warm. They can also be eaten cold.',
    ],
    dietaryTags: ['High-Protein', 'Vegetarian', 'Gluten-Free', 'Low-Carb'],
    allergenTags: ['Eggs', 'Dairy'],
    thumbnail: 'bf-egg-muffins',
    storageInstructions: 'Store in the fridge for up to 3 days. Can be eaten cold or reheated in the microwave for 20 seconds.',
    leftoverSuggestions: 'Pack cold egg muffins in a lunchbox with fruit, or crumble over a salad for a protein boost.',
  }),

  makeRecipe({
    id: 'bf-avo-toast',
    title: 'Avocado on Toast with Egg',
    description: 'Mashed avocado on toast topped with a fried egg. A nutritious and satisfying breakfast.',
    mealCategory: 'Breakfast',
    recipeCategories: ['Breakfast', 'Quick Weekday', 'Healthy', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    difficulty: 'Easy',
    estimatedTotalCost: 35,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Avocado', 1, 'whole', 12),
      ing('Bread', 2, 'slices', 4),
      ing('Eggs', 2, 'whole', 8),
      ing('Cooking oil', 1, 'tsp', 1, { isStaple: true }),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Chilli flakes', 1, 'pinch', 2, { isOptional: true, isStaple: true }),
    ],
    substitutes: [
      { ingredient: 'Avocado', substitute: 'Mashed boiled egg with mayonnaise' },
    ],
    instructions: [
      'Toast the bread slices until golden.',
      'Cut the avocado in half, remove the pit, and scoop the flesh into a bowl. Mash with a fork, adding salt and pepper to taste.',
      'Heat oil in a pan over medium heat. Crack the eggs into the pan and fry to your preference (sunny-side up or over-easy).',
      'Spread the mashed avocado generously over the toasted bread.',
      'Slide the fried eggs on top of the avocado. Sprinkle with chilli flakes if using.',
      'Serve immediately while the egg is warm and the yolk is runny.',
    ],
    dietaryTags: ['High-Protein', 'Vegetarian'],
    allergenTags: ['Eggs', 'Gluten'],
    thumbnail: 'bf-avo-toast',
    storageInstructions: 'Best eaten immediately. Avocado turns brown when stored.',
    leftoverSuggestions: 'Use leftover mashed avocado as a dip with crackers, or add to a chicken mayo sandwich.',
  }),

  makeRecipe({
    id: 'bf-pancakes',
    title: 'Flapjack Pancakes',
    description: 'Small, fluffy pancakes served with syrup or sugar. A weekend breakfast treat.',
    mealCategory: 'Breakfast',
    recipeCategories: ['Breakfast', 'Weekend', 'Vegetarian', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 30,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Flour', 2, 'cups', 5, { isStaple: true }),
      ing('Eggs', 2, 'whole', 8),
      ing('Milk', 1.5, 'cups', 8),
      ing('Sugar', 2, 'tbsp', 2, { isStaple: true }),
      ing('Baking powder', 2, 'tsp', 3, { isStaple: true }),
      ing('Butter', 1, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Golden syrup', 2, 'tbsp', 5, { isOptional: true }),
      ing('Banana', 1, 'whole', 4, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Milk', substitute: 'Water' },
      { ingredient: 'Butter', substitute: 'Cooking oil' },
    ],
    instructions: [
      'In a bowl, sift together the flour, sugar, baking powder and salt.',
      'In a separate bowl, whisk the eggs and milk. Pour the wet ingredients into the dry and stir until just combined. Do not overmix — a few lumps are fine.',
      'Heat a pan over medium-low heat and melt a small amount of butter.',
      'Pour 2-3 tablespoonfuls of batter per pancake into the pan. Cook for 2-3 minutes until bubbles form on the surface and the edges look set.',
      'Flip and cook for another 1-2 minutes until golden brown on both sides.',
      'Repeat with the remaining batter, adding more butter as needed. Serve warm with golden syrup, sugar, or sliced banana.',
    ],
    dietaryTags: ['Vegetarian'],
    allergenTags: ['Eggs', 'Dairy', 'Gluten'],
    thumbnail: 'bf-pancakes',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in a pan or toaster. Can be frozen for up to 1 month.',
    leftoverSuggestions: 'Use leftover pancakes as a base for a trifle with custard and fruit, or spread with peanut butter for a snack.',
  }),
];
