import { makeRecipe, ing } from './helper';

export const lunchRecipes = [
  makeRecipe({
    id: 'ln-leftover-chicken-wrap',
    title: 'Leftover Chicken Wrap',
    description: 'A quick wrap using leftover cooked chicken, fresh vegetables and mayonnaise.',
    mealCategory: 'Lunch',
    recipeCategories: ['Lunch', 'Quick Weekday', 'Quick <30min', 'Leftovers', 'Lunchbox'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: 'Easy',
    estimatedTotalCost: 35,
    equipment: [],
    ingredients: [
      ing('Tortilla wraps', 2, 'whole', 10),
      ing('Leftover chicken', 200, 'g', 0),
      ing('Lettuce', 2, 'leaves', 5),
      ing('Tomatoes', 1, 'whole', 3),
      ing('Mayonnaise', 2, 'tbsp', 8),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cheese', 30, 'g', 6, { isOptional: true }),
      ing('Avocado', 0.5, 'whole', 6, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Tortilla wraps', substitute: 'Bread for a sandwich' },
      { ingredient: 'Leftover chicken', substitute: 'Tinned tuna or ham' },
    ],
    instructions: [
      'Shred or slice the leftover chicken. Wash the lettuce and tomato. Slice the tomato thinly.',
      'Lay the tortilla wraps flat. Spread a tablespoon of mayonnaise over each wrap.',
      'Layer the lettuce leaves, sliced tomato and shredded chicken down the centre of each wrap.',
      'If using cheese, grate and sprinkle over the chicken. If using avocado, slice and add now.',
      'Season with pepper. Fold the sides of the wrap over the filling, then roll up tightly from the bottom.',
      'Cut in half and serve. No cooking required.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Gluten', 'Eggs', 'Dairy'],
    thumbnail: 'ln-wrap',
    storageInstructions: 'Best eaten immediately. If storing, wrap tightly and keep in the fridge for up to 1 day.',
    leftoverSuggestions: 'Unwrap and use the filling in a salad, or add the chicken to a pasta salad.',
  }),

  makeRecipe({
    id: 'ln-tuna-salad',
    title: 'Tuna Salad',
    description: 'A protein-rich salad with tinned tuna, boiled eggs and fresh vegetables.',
    mealCategory: 'Lunch',
    recipeCategories: ['Lunch', 'Quick Weekday', 'Healthy', 'Quick <30min', 'High-Protein', 'Lunchbox'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    difficulty: 'Easy',
    estimatedTotalCost: 45,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Tuna', 1, 'can', 25),
      ing('Eggs', 2, 'whole', 8),
      ing('Lettuce', 4, 'leaves', 5),
      ing('Tomatoes', 1, 'whole', 3),
      ing('Cucumber', 0.5, 'whole', 4),
      ing('Onions', 0.25, 'whole', 2),
      ing('Mayonnaise', 2, 'tbsp', 8),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Sweet corn', 0.5, 'can', 6, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Tuna', substitute: 'Leftover chicken or tinned salmon' },
    ],
    instructions: [
      'Place the eggs in a pot and cover with water. Bring to a boil and cook for 8-10 minutes. Remove, cool under cold water, and peel.',
      'Wash the lettuce, tomato and cucumber. Slice the tomato and cucumber. Finely slice the onion.',
      'Drain the tuna. In a bowl, flake the tuna with a fork. Add the mayonnaise, salt and pepper. Mix well.',
      'Arrange the lettuce leaves on plates. Top with the sliced tomato, cucumber and onion.',
      'Spoon the tuna mixture over the vegetables. If using sweet corn, drain and sprinkle over the top.',
      'Cut the boiled eggs into quarters and arrange on top. Serve immediately.',
    ],
    dietaryTags: ['High-Protein', 'Pescatarian', 'Low-Carb', 'Gluten-Free'],
    allergenTags: ['Fish', 'Eggs'],
    thumbnail: 'ln-tuna-salad',
    storageInstructions: 'Store in the fridge for up to 1 day. If storing, keep the tuna mixture separate from the fresh vegetables.',
    leftoverSuggestions: 'Use leftover tuna mixture as a sandwich filling, or add to a pasta salad with mayonnaise.',
  }),

  makeRecipe({
    id: 'ln-cheese-toastie',
    title: 'Cheese and Tomato Toastie',
    description: 'A crispy, melted cheese and tomato sandwich. A comforting quick lunch.',
    mealCategory: 'Lunch',
    recipeCategories: ['Lunch', 'Quick Weekday', 'Budget', 'Vegetarian', 'Quick <30min', 'Lunchbox'],
    cuisineType: 'South African',
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    difficulty: 'Easy',
    estimatedTotalCost: 25,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Bread', 4, 'slices', 8),
      ing('Cheese', 100, 'g', 15),
      ing('Tomatoes', 1, 'whole', 3),
      ing('Butter', 2, 'tbsp', 4, { isStaple: true }),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Onions', 0.25, 'whole', 2, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Butter', substitute: 'Cooking oil or margarine' },
      { ingredient: 'Cheese', substitute: 'Cheese spread' },
    ],
    instructions: [
      'Grate the cheese. Slice the tomato thinly. If using onion, slice thinly.',
      'Butter one side of each bread slice.',
      'Place two slices butter-side down. Layer with grated cheese, sliced tomato and onion if using. Sprinkle with pepper.',
      'Top with the remaining bread slices, butter-side up.',
      'Heat a pan over medium heat. Place the sandwiches butter-side down in the pan.',
      'Cook for 3-4 minutes until golden brown. Carefully flip and cook for another 3-4 minutes until the cheese is melted and both sides are golden. Serve hot.',
    ],
    dietaryTags: ['Vegetarian'],
    allergenTags: ['Gluten', 'Dairy'],
    thumbnail: 'ln-toastie',
    storageInstructions: 'Best eaten immediately while the cheese is melted.',
    leftoverSuggestions: 'Cut leftover toasties into strips and serve with tomato soup as a dipper.',
  }),

  makeRecipe({
    id: 'ln-leftover-pap-fried',
    title: 'Fried Pap with Tomato Relish',
    description: 'Leftover stiff pap sliced and fried until crispy, served with fresh tomato relish.',
    mealCategory: 'Lunch',
    recipeCategories: ['Lunch', 'Budget', 'Leftovers', 'Vegetarian', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 20,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Leftover pap', 500, 'g', 0),
      ing('Tomatoes', 3, 'whole', 9),
      ing('Onions', 1, 'whole', 3),
      ing('Cooking oil', 3, 'tbsp', 3, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Sugar', 1, 'tsp', 1, { isStaple: true }),
      ing('Vinegar', 1, 'tbsp', 2, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Chilli', 1, 'whole', 2, { isOptional: true }),
    ],
    instructions: [
      'Cut the leftover pap into slices about 2cm thick. The pap should be cold and firm from the fridge.',
      'Make the relish: dice the tomatoes and onion. Crush the garlic.',
      'Heat 1 tablespoon of oil in a pan over medium heat. Add the onion and garlic, fry for 3 minutes until soft.',
      'Add the diced tomatoes, salt, pepper, sugar and vinegar. If using chilli, add now. Simmer for 8-10 minutes until the tomatoes break down into a chunky sauce.',
      'While the relish simmers, heat 2 tablespoons of oil in another pan over medium-high heat. Fry the pap slices for 3-4 minutes per side until crispy and golden.',
      'Serve the fried pap hot with the tomato relish spooned over the top.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free'],
    allergenTags: [],
    thumbnail: 'ln-fried-pap',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat the fried pap in a pan to restore crispiness.',
    leftoverSuggestions: 'Crumble leftover fried pap into the tomato relish and serve as a warm salad.',
  }),

  makeRecipe({
    id: 'ln-chicken-mayo-rice',
    title: 'Chicken Mayo Rice Salad',
    description: 'Cold rice salad with leftover chicken, mayonnaise and vegetables. A filling lunch.',
    mealCategory: 'Lunch',
    recipeCategories: ['Lunch', 'Quick Weekday', 'Leftovers', 'Quick <30min', 'Lunchbox'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 35,
    equipment: [],
    ingredients: [
      ing('Leftover rice', 4, 'cups', 0),
      ing('Leftover chicken', 200, 'g', 0),
      ing('Mayonnaise', 3, 'tbsp', 12),
      ing('Carrots', 1, 'whole', 3),
      ing('Sweet corn', 1, 'can', 12),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
    ],
    instructions: [
      'Ensure the leftover rice and chicken are cold. Shred the chicken.',
      'Grate the carrot. Drain the sweet corn. If using cheese, grate it.',
      'In a large bowl, combine the cold rice, shredded chicken, grated carrot and drained corn.',
      'Add the mayonnaise, salt and pepper. Mix until everything is evenly coated.',
      'If using cheese, fold it in. Adjust seasoning to taste.',
      'Serve cold. No cooking required.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Eggs', 'Dairy'],
    thumbnail: 'ln-chicken-rice-salad',
    storageInstructions: 'Store in the fridge for up to 2 days. Do not freeze.',
    leftoverSuggestions: 'Use leftover rice salad as a filling for wraps, or add to a lettuce cup for a low-carb lunch.',
  }),

  makeRecipe({
    id: 'ln-baked-beans-toast',
    title: 'Baked Beans on Toast',
    description: 'Warm baked beans spooned over crispy toast. A quick, budget-friendly lunch.',
    mealCategory: 'Lunch',
    recipeCategories: ['Lunch', 'Quick Weekday', 'Budget', 'Vegetarian', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 2,
    cookTime: 8,
    servings: 2,
    difficulty: 'Easy',
    estimatedTotalCost: 20,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Baked beans', 1, 'can', 15),
      ing('Bread', 2, 'slices', 4),
      ing('Butter', 1, 'tbsp', 2, { isStaple: true }),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cheese', 30, 'g', 6, { isOptional: true }),
      ing('Eggs', 1, 'whole', 4, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Butter', substitute: 'Cooking oil or margarine' },
    ],
    instructions: [
      'Empty the baked beans into a small pot. Place over medium heat and warm through for 5 minutes, stirring occasionally. Do not boil.',
      'Toast the bread slices until golden. Butter the toast.',
      'If using cheese, grate it. If using an egg, fry it in a pan with a little oil.',
      'Place the toast on plates. Spoon the warm baked beans generously over the toast.',
      'If using cheese, sprinkle over the beans. If using a fried egg, place on top.',
      'Season with pepper and serve immediately.',
    ],
    dietaryTags: ['Vegetarian', 'High-Fiber'],
    allergenTags: ['Gluten', 'Dairy'],
    thumbnail: 'ln-beans-toast',
    storageInstructions: 'Best eaten immediately. Store leftover beans separately from toast in the fridge for up to 1 day.',
    leftoverSuggestions: 'Use leftover baked beans in a breakfast hash with potatoes and eggs, or as a topping for jacket potatoes.',
  }),

  makeRecipe({
    id: 'ln-egg-salad-sandwich',
    title: 'Egg Salad Sandwich',
    description: 'Creamy mashed egg with mayonnaise in a soft bread sandwich. A classic lunch.',
    mealCategory: 'Lunch',
    recipeCategories: ['Lunch', 'Quick Weekday', 'Budget', 'Vegetarian', 'Quick <30min', 'Lunchbox'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: 'Easy',
    estimatedTotalCost: 25,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Eggs', 4, 'whole', 16),
      ing('Bread', 4, 'slices', 8),
      ing('Mayonnaise', 3, 'tbsp', 12),
      ing('Onions', 0.25, 'whole', 2),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Pepper', 1, 'pinch', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Lettuce', 2, 'leaves', 5, { isOptional: true }),
    ],
    instructions: [
      'Place the eggs in a pot and cover with water. Bring to a boil and cook for 8-10 minutes. Cool under cold water and peel.',
      'Finely dice the onion. Place in a bowl with the mayonnaise, salt and pepper.',
      'Grate or mash the boiled eggs into the bowl. Mix until well combined and creamy.',
      'Lay out the bread slices. If using lettuce, place a leaf on two slices.',
      'Spoon the egg mixture over the lettuce (or directly onto the bread). Top with the remaining bread slices.',
      'Cut in half and serve. Can be wrapped for a lunchbox.',
    ],
    dietaryTags: ['Vegetarian', 'High-Protein'],
    allergenTags: ['Eggs', 'Gluten'],
    thumbnail: 'ln-egg-sandwich',
    storageInstructions: 'Store in the fridge for up to 1 day. Wrap tightly to keep the bread fresh.',
    leftoverSuggestions: 'Use leftover egg salad as a dip with crackers, or serve on a bed of lettuce as a salad.',
  }),
];
