import { makeRecipe, ing } from './helper';

export const onePotRecipes = [
  makeRecipe({
    id: 'op-chicken-rice-pot',
    title: 'One-Pot Chicken and Rice',
    description: 'Chicken and rice cooked together in one pot with vegetables and spices. Minimal washing up.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Budget', 'Dinner', 'Quick Weekday'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 75,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Chicken portions', 500, 'g', 45),
      ing('Rice', 2, 'cups', 16),
      ing('Onions', 1, 'whole', 3),
      ing('Carrots', 2, 'whole', 6),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Curry powder', 1, 'tbsp', 3, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 4, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Peas', 0.5, 'cup', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Chicken portions', substitute: 'Sausages or mince' },
      { ingredient: 'Curry powder', substitute: 'Mixed herbs' },
    ],
    instructions: [
      'Dice the onion and carrots. Crush the garlic. Cut the chicken portions into smaller pieces if large.',
      'Heat the oil in a large pot over medium-high heat. Brown the chicken pieces for 3-4 minutes per side until golden. Remove and set aside.',
      'In the same pot, add the onion and garlic. Fry for 3 minutes until soft. Add the curry powder and tomato paste. Stir for 1 minute until fragrant.',
      'Add the rice and diced carrots. Stir to coat the rice in the paste.',
      'Pour in the water. Add salt and pepper. Stir well, scraping any browned bits from the bottom of the pot.',
      'Return the chicken pieces to the pot, nesting them into the rice. Bring to a boil.',
      'Cover, reduce heat to low, and simmer for 20 minutes. Do not lift the lid during cooking. If using peas, add them in the last 5 minutes.',
      'The dish is ready when the rice has absorbed all the water, the chicken is cooked through (internal temp 75°C, no pink), and the vegetables are tender. Rest for 5 minutes before serving.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: [],
    thumbnail: 'op-chicken-rice',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in the microwave or on the stove with a splash of water.',
    leftoverSuggestions: 'Fry leftover chicken and rice in a pan with egg for chicken fried rice, or add to a soup.',
  }),

  makeRecipe({
    id: 'op-mince-potato-pot',
    title: 'One-Pot Mince and Potato',
    description: 'Beef mince and potatoes cooked together in a rich tomato sauce. A complete meal in one pot.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Budget', 'Dinner', 'Quick Weekday'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 70,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Mince', 500, 'g', 55),
      ing('Potatoes', 4, 'whole', 12),
      ing('Onions', 1, 'whole', 3),
      ing('Tomato paste', 3, 'tbsp', 7, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Curry powder', 1, 'tbsp', 3, { isStaple: true }),
      ing('Stock cubes', 1, 'whole', 2, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 2, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Carrots', 1, 'whole', 3, { isOptional: true }),
      ing('Peas', 0.5, 'cup', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Mince', substitute: 'Sausages, sliced' },
    ],
    instructions: [
      'Peel and cut the potatoes into 3cm chunks. Dice the onion. Crush the garlic. If using carrots, dice them.',
      'Heat oil in a large pot over medium-high heat. Add the mince and brown for 5-7 minutes, breaking it up with a spoon, until no pink remains.',
      'Add the onion and garlic. Fry for 3 minutes until the onion is soft.',
      'Stir in the curry powder and tomato paste. Cook for 1 minute until fragrant.',
      'Add the potatoes (and carrots if using). Crumble in the stock cube. Pour in the water. Add salt and pepper. Stir well.',
      'Bring to a boil, then cover and reduce heat to low. Simmer for 25-30 minutes, stirring occasionally, until the potatoes are tender and the sauce has thickened.',
      'If using peas, add in the last 5 minutes. The dish is ready when the potatoes are soft and the mince is cooked through. Serve hot.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: [],
    thumbnail: 'op-mince-potato',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat on the stove over medium heat until bubbling.',
    leftoverSuggestions: 'Mash leftover potatoes and mince together, shape into patties, and fry for potato cakes.',
  }),

  makeRecipe({
    id: 'op-vegetable-soup',
    title: 'One-Pot Vegetable Soup',
    description: 'A hearty vegetable soup with potatoes, carrots and beans. Budget-friendly and filling.',
    mealCategory: 'Dinner',
    recipeCategories: ['Budget', 'One-Pot', 'Vegetarian', 'Dinner', 'Healthy'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: 'Easy',
    estimatedTotalCost: 45,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Potatoes', 3, 'whole', 9),
      ing('Carrots', 3, 'whole', 9),
      ing('Onions', 1, 'whole', 3),
      ing('Tomatoes', 2, 'whole', 6),
      ing('Baked beans', 1, 'can', 15),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Curry powder', 1, 'tsp', 2, { isStaple: true }),
      ing('Stock cubes', 2, 'whole', 4, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 6, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Cabbage', 1, 'cup', 5, { isOptional: true }),
      ing('Sweet corn', 1, 'can', 12, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Baked beans', substitute: 'Tinned butter beans or lentils' },
    ],
    instructions: [
      'Peel and dice the potatoes and carrots into 2cm chunks. Dice the onion and tomatoes. Crush the garlic. If using cabbage, shred it.',
      'Heat oil in a large pot over medium heat. Add the onion and garlic, fry for 3 minutes until soft.',
      'Add the curry powder and stir for 30 seconds until fragrant.',
      'Add the potatoes, carrots and tomatoes. Stir to coat. Cook for 2 minutes.',
      'Crumble in the stock cubes and pour in the water. Add salt and pepper. Bring to a boil.',
      'Cover, reduce heat to low, and simmer for 20 minutes until the vegetables are tender.',
      'Add the baked beans (and corn and cabbage if using). Simmer for another 5-10 minutes until the cabbage is soft and the beans are heated through. Taste and adjust seasoning. Serve hot with bread.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free', 'Gluten-Free', 'High-Fiber'],
    allergenTags: [],
    thumbnail: 'op-veg-soup',
    storageInstructions: 'Store in the fridge for up to 3 days. The soup tastes even better the next day. Can be frozen for up to 1 month.',
    leftoverSuggestions: 'Blend leftover soup into a smooth cream soup, or drain the liquid and use the vegetables as a baked potato topping.',
  }),

  makeRecipe({
    id: 'op-sausage-beans',
    title: 'One-Pot Sausage and Beans',
    description: 'Sausages simmered with baked beans in a tomato sauce. A quick, filling one-pot dinner.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Budget', 'Quick Weekday', 'Dinner', 'Quick <30min'],
    cuisineType: 'South African',
    prepTime: 5,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 60,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Sausages', 6, 'whole', 55),
      ing('Baked beans', 2, 'cans', 30),
      ing('Onions', 1, 'whole', 3),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 0.5, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Chilli', 1, 'whole', 2, { isOptional: true }),
      ing('Sugar', 1, 'tsp', 1, { isOptional: true, isStaple: true }),
    ],
    substitutes: [
      { ingredient: 'Sausages', substitute: 'Boerewors or Viennas' },
    ],
    instructions: [
      'Slice the sausages into 3cm pieces. Dice the onion. Crush the garlic.',
      'Heat oil in a pot over medium-high heat. Brown the sausage pieces for 3-4 minutes until golden. Remove excess fat if desired.',
      'Add the onion and garlic to the pot. Fry for 3 minutes until the onion is soft.',
      'Stir in the tomato paste and cook for 1 minute. If using chilli and sugar, add now.',
      'Pour in the baked beans with their sauce. Add salt and pepper. Stir well.',
      'Bring to a gentle simmer. Cover, reduce heat to low, and cook for 15-20 minutes, stirring occasionally to prevent sticking.',
      'The dish is ready when the sausages are cooked through (no pink inside) and the sauce has thickened. Serve hot with bread or rice.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: [],
    thumbnail: 'op-sausage-beans',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat on the stove until bubbling.',
    leftoverSuggestions: 'Serve leftover sausage and beans on toast for breakfast, or wrap in a tortilla with cheese.',
  }),

  makeRecipe({
    id: 'op-chicken-stew-pot',
    title: 'One-Pot Chicken Stew',
    description: 'Chicken pieces simmered with potatoes and vegetables in a rich gravy. All in one pot.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 85,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Chicken portions', 8, 'whole', 72),
      ing('Potatoes', 4, 'whole', 12),
      ing('Carrots', 2, 'whole', 6),
      ing('Onions', 1, 'whole', 3),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Garlic', 3, 'cloves', 4, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Flour', 2, 'tbsp', 2, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Peas', 0.5, 'cup', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Chicken portions', substitute: 'Beef stewing meat' },
    ],
    instructions: [
      'Cut the chicken portions into smaller pieces if large. Peel and cut the potatoes into 4cm chunks. Dice the carrots and onion. Crush the garlic.',
      'Heat oil in a large pot over medium-high heat. Brown the chicken pieces for 3-4 minutes per side until golden. Remove and set aside.',
      'In the same pot, add the onion and garlic. Fry for 3 minutes. Sprinkle in the flour and stir for 1 minute to make a roux.',
      'Gradually whisk in the water to prevent lumps. Add the tomato paste, mixed herbs, salt and pepper. Stir until smooth.',
      'Return the chicken to the pot. Add the potatoes and carrots. Bring to a boil.',
      'Cover, reduce heat to low, and simmer for 35-40 minutes until the chicken is tender and cooked through (internal temp 75°C, no pink, juices run clear) and the vegetables are soft.',
      'If using peas, add in the last 5 minutes. The stew is ready when the gravy has thickened and coats the back of a spoon. Serve hot with rice or bread.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: ['Gluten'],
    thumbnail: 'op-chicken-stew',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat on the stove over medium heat until bubbling.',
    leftoverSuggestions: 'Shred leftover chicken and mix with the gravy for a pie filling, or serve over toast.',
  }),

  makeRecipe({
    id: 'op-lentil-curry',
    title: 'One-Pot Lentil Curry',
    description: 'Red lentils cooked in a spiced curry with potatoes. A budget-friendly, protein-rich meal.',
    mealCategory: 'Dinner',
    recipeCategories: ['Budget', 'One-Pot', 'Vegetarian', 'Vegan', 'Dinner', 'Healthy'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 35,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Red lentils', 1.5, 'cups', 15),
      ing('Potatoes', 2, 'whole', 6),
      ing('Onions', 1, 'whole', 3),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Garlic', 3, 'cloves', 4, { isStaple: true }),
      ing('Curry powder', 2, 'tbsp', 5, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 4, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Coriander', 1, 'handful', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Red lentils', substitute: 'Split peas (will take longer to cook)' },
    ],
    instructions: [
      'Rinse the lentils in cold water and drain. Peel and dice the potatoes. Dice the onion. Crush the garlic.',
      'Heat oil in a pot over medium heat. Add the onion and garlic, fry for 3 minutes until soft.',
      'Add the curry powder and stir for 1 minute until fragrant. Add the tomato paste and cook for another 30 seconds.',
      'Add the rinsed lentils, diced potatoes, salt and pepper. Pour in the water. Stir well.',
      'Bring to a boil, then cover and reduce heat to low. Simmer for 25-30 minutes, stirring occasionally, until the lentils have broken down and the potatoes are tender.',
      'The curry is ready when it has a thick, porridge-like consistency. If too thick, add a little water. If too thin, simmer uncovered for a few more minutes.',
      'If using coriander, stir in just before serving. Taste and adjust seasoning. Serve hot with rice or bread.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free', 'Gluten-Free', 'High-Fiber', 'High-Protein'],
    allergenTags: [],
    thumbnail: 'op-lentil-curry',
    storageInstructions: 'Store in the fridge for up to 3 days. Reheat on the stove with a splash of water. Can be frozen for up to 1 month.',
    leftoverSuggestions: 'Use leftover lentil curry as a filling for samosas or pies, or serve with pap for a traditional meal.',
  }),

  makeRecipe({
    id: 'op-fish-potato-pot',
    title: 'One-Pot Fish and Potato Curry',
    description: 'Fish fillets and potatoes simmered in a mild curry sauce. A simple one-pot dinner.',
    mealCategory: 'Dinner',
    recipeCategories: ['One-Pot', 'Quick Weekday', 'Dinner', 'Pescatarian'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 75,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Fish', 4, 'fillets', 55),
      ing('Potatoes', 3, 'whole', 9),
      ing('Onions', 1, 'whole', 3),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Curry powder', 1, 'tbsp', 3, { isStaple: true }),
      ing('Coconut milk', 1, 'can', 20),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 1, 'cup', 0),
    ],
    optionalIngredients: [
      ing('Lemon', 0.5, 'whole', 4, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Coconut milk', substitute: 'Fresh milk with a pinch of sugar' },
    ],
    instructions: [
      'Cut the fish fillets into 4cm pieces. Peel and cut the potatoes into 3cm chunks. Dice the onion. Crush the garlic.',
      'Heat oil in a pot over medium heat. Add the onion and garlic, fry for 3 minutes until soft.',
      'Add the curry powder and stir for 1 minute. Add the tomato paste and cook for 30 seconds.',
      'Add the potatoes, water, salt and pepper. Bring to a boil, then cover and simmer for 15 minutes until the potatoes are almost tender.',
      'Gently add the fish pieces to the pot. Pour in the coconut milk. Stir gently to avoid breaking the fish.',
      'Cover and simmer for 5-8 minutes until the fish is opaque and flakes easily with a fork. Do not overcook or the fish will fall apart.',
      'If using lemon, squeeze juice over just before serving. Taste and adjust seasoning. Serve hot with rice.',
    ],
    dietaryTags: ['Pescatarian', 'High-Protein', 'Dairy-Free'],
    allergenTags: ['Fish'],
    thumbnail: 'op-fish-curry',
    storageInstructions: 'Store in the fridge for up to 1 day. Reheat gently on the stove — do not boil or the fish will break up.',
    leftoverSuggestions: 'Flake leftover fish into the curry sauce and serve over toast, or use as a filling for a fish pie.',
  }),

  makeRecipe({
    id: 'op-beef-stew-pot',
    title: 'One-Pot Beef Stew',
    description: 'Tender beef pieces with potatoes and carrots in a rich gravy. A classic one-pot meal.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Dinner', 'Weekend'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 90,
    servings: 6,
    difficulty: 'Medium',
    estimatedTotalCost: 110,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Beef stewing meat', 1, 'kg', 95),
      ing('Potatoes', 4, 'whole', 12),
      ing('Carrots', 3, 'whole', 9),
      ing('Onions', 2, 'whole', 6),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Garlic', 3, 'cloves', 4, { isStaple: true }),
      ing('Flour', 2, 'tbsp', 2, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 4, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Red wine', 0.5, 'cup', 30, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Beef stewing meat', substitute: 'Oxtail or lamb pieces' },
    ],
    instructions: [
      'Cut the beef into 3cm cubes if not already cut. Peel and cut the potatoes into 4cm chunks. Dice the carrots and onions. Crush the garlic.',
      'Toss the beef in flour, salt and pepper until lightly coated.',
      'Heat oil in a large pot over medium-high heat. Brown the beef in batches for 3-4 minutes per side until deeply coloured. Do not overcrowd the pot. Remove and set aside.',
      'Add the onions and garlic to the pot. Fry for 3 minutes. Add the tomato paste and mixed herbs. Stir for 1 minute.',
      'Return the beef to the pot. Pour in the water (and red wine if using). Bring to a boil.',
      'Cover, reduce heat to low, and simmer for 60 minutes, stirring occasionally.',
      'Add the potatoes and carrots. Simmer for another 30 minutes until the beef is tender and the vegetables are soft. The stew is ready when the meat falls apart easily with a fork. Serve hot with rice or bread.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: ['Gluten'],
    thumbnail: 'op-beef-stew',
    storageInstructions: 'Store in the fridge for up to 3 days. The stew tastes better the next day. Can be frozen for up to 2 months.',
    leftoverSuggestions: 'Use leftover stew as a pie filling with pastry on top, or serve over toast for a quick dinner.',
  }),

  makeRecipe({
    id: 'op-chickpea-curry',
    title: 'One-Pot Chickpea and Potato Curry',
    description: 'Tinned chickpeas and potatoes in a fragrant curry sauce. A budget-friendly vegetarian meal.',
    mealCategory: 'Dinner',
    recipeCategories: ['Budget', 'One-Pot', 'Vegetarian', 'Vegan', 'Dinner', 'Healthy', 'Quick Weekday'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 40,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Chickpeas', 2, 'cans', 25),
      ing('Potatoes', 3, 'whole', 9),
      ing('Onions', 1, 'whole', 3),
      ing('Tomatoes', 2, 'whole', 6),
      ing('Garlic', 3, 'cloves', 4, { isStaple: true }),
      ing('Curry powder', 2, 'tbsp', 5, { isStaple: true }),
      ing('Tomato paste', 1, 'tbsp', 3, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 1.5, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Coconut milk', 0.5, 'can', 10, { isOptional: true }),
      ing('Spinach', 1, 'cup', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Chickpeas', substitute: 'Butter beans or kidney beans' },
    ],
    instructions: [
      'Drain and rinse the chickpeas. Peel and dice the potatoes. Dice the onion and tomatoes. Crush the garlic.',
      'Heat oil in a pot over medium heat. Add the onion and garlic, fry for 3 minutes until soft.',
      'Add the curry powder and stir for 1 minute until fragrant. Add the tomato paste and cook for 30 seconds.',
      'Add the diced potatoes and tomatoes. Stir to coat. Cook for 2 minutes.',
      'Pour in the water. Add salt and pepper. Bring to a boil, then cover and simmer for 15 minutes until the potatoes are almost tender.',
      'Add the drained chickpeas. If using coconut milk, pour it in now. Simmer for another 5-10 minutes until the potatoes are fully soft and the sauce has thickened.',
      'If using spinach, stir in during the last 2 minutes until wilted. Taste and adjust seasoning. Serve hot with rice or bread.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free', 'Gluten-Free', 'High-Fiber', 'High-Protein'],
    allergenTags: [],
    thumbnail: 'op-chickpea-curry',
    storageInstructions: 'Store in the fridge for up to 3 days. Reheat on the stove with a splash of water. Can be frozen for up to 1 month.',
    leftoverSuggestions: 'Mash leftover curry and use as a filling for toasted sandwiches, or serve with pap.',
  }),
];
