import { makeRecipe, ing } from './helper';

export const stovetopRecipes = [
  makeRecipe({
    id: 'st-chicken-veg-stew',
    title: 'Chicken and Vegetable Stew',
    description: 'A hearty one-pot stew with chicken, potatoes and carrots in a rich tomato broth. A South African family favourite.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Stovetop', 'No-Oven', 'Soup and Stew', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    difficulty: 'Easy',
    estimatedTotalCost: 120,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Chicken portions', 1, 'kg', 90),
      ing('Potatoes', 4, 'whole', 12),
      ing('Carrots', 3, 'whole', 9),
      ing('Onions', 2, 'whole', 6),
      ing('Tomatoes', 4, 'whole', 12),
      ing('Garlic', 3, 'cloves', 5, { isStaple: true }),
      ing('Curry powder', 2, 'tsp', 3, { isStaple: true }),
      ing('Stock cubes', 2, 'cubes', 4, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Green pepper', 1, 'whole', 8),
    ],
    substitutes: [
      { ingredient: 'Chicken portions', substitute: 'Chicken drumsticks or a whole chicken cut into pieces' },
      { ingredient: 'Curry powder', substitute: 'Paprika and cumin mixed together' },
    ],
    instructions: [
      'Cut chicken portions into serving-size pieces if needed. Peel and chop potatoes into large chunks. Slice carrots into rounds. Dice onions and tomatoes finely. Crush garlic cloves.',
      'Heat 2 tablespoons of cooking oil in a large pot over medium-high heat. Season chicken with salt and pepper, then brown the pieces for 3 minutes per side until golden. Remove chicken and set aside.',
      'In the same pot, add the diced onions and garlic. Fry over medium heat for 3 minutes until soft and translucent. Add the curry powder and stir for 30 seconds until fragrant.',
      'Add the chopped tomatoes and cook for 5 minutes, stirring occasionally, until they break down into a sauce. The mixture is ready when it thickens slightly.',
      'Return the chicken to the pot. Add the potatoes, carrots, stock cubes and 3 cups of water. Bring to a boil, then reduce heat to low.',
      'Cover the pot and simmer for 30 minutes, stirring every 10 minutes, until the chicken is cooked through (no pink inside and juices run clear) and the vegetables are tender when pierced with a fork.',
      'Taste the broth and adjust seasoning with salt and pepper. Serve hot in bowls with rice or pap on the side.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: [],
    thumbnail: 'stew',
    storageInstructions: 'Cool completely, then store in an airtight container in the fridge for up to 3 days. Reheat on the stove over medium heat until bubbling hot throughout.',
    leftoverSuggestions: 'Shred leftover chicken and mix with the remaining sauce. Serve on bread rolls for a hearty sandwich, or thicken the broth and serve over rice the next day.',
  }),

  makeRecipe({
    id: 'st-beef-curry-rice',
    title: 'Beef Mince Curry and Rice',
    description: 'Spiced beef mince curry served over fluffy white rice. Quick to prepare and perfect for weeknight dinners.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Budget', 'Family Dinner', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 110,
    equipment: ['Stove', 'Pan', 'Pot'],
    ingredients: [
      ing('Mince', 500, 'g', 55),
      ing('Rice', 2, 'cups', 15),
      ing('Onions', 2, 'whole', 6),
      ing('Tomatoes', 3, 'whole', 9),
      ing('Garlic', 3, 'cloves', 5, { isStaple: true }),
      ing('Ginger', 1, 'tsp', 3, { isStaple: true }),
      ing('Curry powder', 3, 'tsp', 4, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Coriander', 1, 'handful', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Beef mince', substitute: 'Lamb mince or chicken mince' },
      { ingredient: 'Curry powder', substitute: 'Garam masala with extra turmeric' },
    ],
    instructions: [
      'Finely chop the onions and tomatoes. Crush or grate the garlic and ginger. Rinse rice under cold water until the water runs clear.',
      'Place rice and 3 cups of water in a pot with a pinch of salt. Bring to a boil, then reduce to the lowest heat, cover tightly, and cook for 18 minutes without lifting the lid. Remove from heat and rest for 5 minutes.',
      'Meanwhile, heat 2 tablespoons of oil in a large pan over medium-high heat. Add the mince and break it apart with a spoon. Fry for 5-7 minutes until browned all the way through with no raw pink spots.',
      'Add the chopped onions to the mince and cook for 3 minutes until soft. Stir in the garlic, ginger and curry powder. Cook for 1 minute until the spices are fragrant, being careful not to burn them.',
      'Add the chopped tomatoes and 1 cup of water. Stir well, then reduce heat to medium-low. Simmer uncovered for 20 minutes, stirring every 5 minutes, until the sauce thickens and coats the mince.',
      'Taste and season with salt and pepper. The curry is ready when the mince is fully cooked (no pink remaining) and the sauce is thick enough to coat the back of a spoon.',
      'Fluff the rice with a fork. Serve the curry mince spooned over the rice. Garnish with fresh coriander if available.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: [],
    thumbnail: 'curry',
    storageInstructions: 'Store the curry and rice in separate airtight containers in the fridge for up to 3 days. Reheat the curry in a pan over medium heat until steaming hot. Reheat rice with a splash of water in the microwave.',
    leftoverSuggestions: 'Use leftover curry mince as a filling for vetkoek, or spread on bread for a spicy sandwich. Leftover rice can be turned into egg fried rice.',
  }),

  makeRecipe({
    id: 'st-pap-tomato-relish',
    title: 'Pap and Tomato Relish',
    description: 'Classic South African stiff pap served with a tangy tomato and onion relish. Affordable and filling.',
    mealCategory: 'Dinner',
    recipeCategories: ['Budget', 'Stovetop', 'No-Oven', 'Vegetarian', 'Dinner', 'One-Pot'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 55,
    equipment: ['Stove', 'Pot', 'Pan'],
    ingredients: [
      ing('Maize meal', 3, 'cups', 20),
      ing('Tomatoes', 4, 'whole', 12),
      ing('Onions', 1, 'whole', 3),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Sugar', 1, 'tsp', 1, { isStaple: true }),
      ing('Vinegar', 1, 'tbsp', 2, { isStaple: true }),
      ing('Water', 4, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Green pepper', 1, 'whole', 8),
      ing('Chilli', 1, 'whole', 3, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Maize meal', substitute: 'Instant pap or polenta' },
      { ingredient: 'Vinegar', substitute: 'Lemon juice' },
    ],
    instructions: [
      'Bring 4 cups of water to a rolling boil in a medium pot with 1 teaspoon of salt. Dice the onions and tomatoes finely.',
      'Slowly pour the maize meal into the boiling water in a steady stream, stirring constantly with a wooden spoon to prevent lumps.',
      'Reduce heat to low. Cover the pot and cook for 15 minutes, stirring vigorously every 5 minutes to prevent sticking. The pap is ready when it pulls away from the sides of the pot and is smooth.',
      'While the pap cooks, heat 2 tablespoons of oil in a pan over medium heat. Add the diced onions and fry for 3 minutes until soft.',
      'Add the diced tomatoes, sugar and vinegar to the pan. Simmer for 10 minutes over medium-low heat, stirring occasionally, until the relish thickens into a jammy consistency.',
      'Taste the relish and adjust with a pinch of salt. If using green pepper, add it with the tomatoes.',
      'Spoon the pap into a bowl or shape into rounds. Top generously with the warm tomato relish and serve immediately.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free'],
    allergenTags: [],
    thumbnail: 'pap',
    storageInstructions: 'Store pap and relish separately in the fridge for up to 2 days. Reheat pap in the microwave with a splash of water. Reheat relish in a pan over medium heat.',
    leftoverSuggestions: 'Leftover pap can be sliced and grilled in a pan until crispy, then served with the relish as a snack. Leftover relish is excellent on sandwiches or boerewors rolls.',
  }),

  makeRecipe({
    id: 'st-pap-mince',
    title: 'Pap with Mince',
    description: 'Soft pap topped with a savoury mince sauce — a beloved township comfort food combination.',
    mealCategory: 'Dinner',
    recipeCategories: ['Budget', 'Family Dinner', 'Stovetop', 'No-Oven', 'Dinner', 'One-Pot'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 75,
    equipment: ['Stove', 'Pot', 'Pan'],
    ingredients: [
      ing('Maize meal', 2, 'cups', 15),
      ing('Mince', 400, 'g', 45),
      ing('Onions', 1, 'whole', 3),
      ing('Tomatoes', 2, 'whole', 6),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Beef stock cubes', 1, 'cube', 2, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    substitutes: [
      { ingredient: 'Beef mince', substitute: 'Soya mince for a vegetarian version' },
      { ingredient: 'Tomato paste', substitute: 'Extra fresh tomatoes, chopped fine' },
    ],
    instructions: [
      'Bring 3 cups of water to a boil in a pot with a pinch of salt. Finely dice the onion and tomatoes.',
      'Slowly whisk the maize meal into the boiling water. Reduce to low heat, cover, and cook for 15 minutes, stirring every 5 minutes until smooth and thick.',
      'While the pap cooks, heat 2 tablespoons of oil in a pan over medium-high heat. Add the mince and brown for 5-7 minutes, breaking it apart until no pink remains.',
      'Add the diced onion to the mince and fry for 3 minutes until soft. Stir in the tomato paste and cook for 1 minute.',
      'Add the chopped tomatoes, stock cube and 1 cup of water. Reduce heat to medium-low and simmer for 15 minutes, stirring occasionally, until the sauce thickens.',
      'Season with salt and pepper to taste. The mince is cooked when the sauce coats the meat and has reduced to a gravy consistency.',
      'Spoon the pap into bowls and top with the savoury mince sauce. Serve hot.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: [],
    thumbnail: 'pap-mince',
    storageInstructions: 'Store pap and mince separately in the fridge for up to 3 days. Reheat mince in a pan over medium heat until bubbling. Reheat pap with a splash of water in the microwave.',
    leftoverSuggestions: 'Shape leftover pap into balls, coat in flour and pan-fry until golden for a crispy snack. The mince sauce works well as a vetkoek filling.',
  }),

  makeRecipe({
    id: 'st-chicken-curry',
    title: 'Chicken Curry',
    description: 'A fragrant chicken curry with tender pieces in a spiced tomato and onion gravy. Mild enough for the whole family.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'Stovetop', 'No-Oven', 'Dinner', 'One-Pot'],
    cuisineType: 'South African',
    prepTime: 20,
    cookTime: 40,
    servings: 5,
    difficulty: 'Medium',
    estimatedTotalCost: 105,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Chicken portions', 1, 'kg', 90),
      ing('Onions', 2, 'whole', 6),
      ing('Tomatoes', 4, 'whole', 12),
      ing('Garlic', 4, 'cloves', 5, { isStaple: true }),
      ing('Ginger', 1, 'tbsp', 3, { isStaple: true }),
      ing('Curry powder', 3, 'tbsp', 5, { isStaple: true }),
      ing('Turmeric', 1, 'tsp', 2, { isStaple: true }),
      ing('Cooking oil', 3, 'tbsp', 3, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 2, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Potatoes', 3, 'whole', 9, { isOptional: true }),
      ing('Coriander', 1, 'handful', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Curry powder', substitute: '2 tsp cumin, 2 tsp coriander powder, 1 tsp chilli powder' },
      { ingredient: 'Chicken portions', substitute: 'Chicken breast fillets, cut into chunks' },
    ],
    instructions: [
      'Cut chicken into serving pieces. Finely chop onions and tomatoes. Crush garlic and grate ginger.',
      'Heat 3 tablespoons of oil in a large pot over medium-high heat. Add the onions and fry for 5 minutes until golden brown and soft.',
      'Add the garlic, ginger, curry powder and turmeric. Stir continuously for 1 minute until the spices are fragrant and well combined.',
      'Add the chicken pieces to the pot. Stir to coat in the spice mixture and fry for 5 minutes until the chicken is sealed and lightly browned on all sides.',
      'Add the chopped tomatoes and 2 cups of water. If using potatoes, peel and cut into chunks and add now. Bring to a boil, then reduce to medium-low heat.',
      'Cover and simmer for 25 minutes, stirring every 10 minutes. The chicken is cooked when it reaches an internal temperature of 75°C and the juices run clear with no pink.',
      'Remove the lid and simmer for 5 more minutes if the sauce is too thin. Taste and adjust salt. Serve with rice or roti, garnished with coriander.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: [],
    thumbnail: 'chicken-curry',
    storageInstructions: 'Store in an airtight container in the fridge for up to 3 days. Curry flavours deepen overnight. Reheat on the stove over medium heat until bubbling throughout.',
    leftoverSuggestions: 'Shred leftover chicken and use the curry sauce as a topping for chips or as a filling for wraps with fresh lettuce.',
  }),

  makeRecipe({
    id: 'st-chicken-pasta',
    title: 'Chicken Pasta',
    description: 'Simple chicken and pasta in a tomato-based sauce. A quick family dinner that children love.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Family Dinner', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 95,
    equipment: ['Stove', 'Pot', 'Pan'],
    ingredients: [
      ing('Chicken breast', 500, 'g', 65),
      ing('Pasta', 400, 'g', 20),
      ing('Tomatoes', 3, 'whole', 9),
      ing('Onions', 1, 'whole', 3),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true, substitute: 'Use extra mixed herbs' }),
    ],
    substitutes: [
      { ingredient: 'Chicken breast', substitute: 'Chicken thighs, deboned and skinned' },
      { ingredient: 'Pasta', substitute: 'Any pasta shape — macaroni, penne, or spaghetti' },
    ],
    instructions: [
      'Fill a large pot with water, add a generous pinch of salt and bring to a boil. Dice the chicken breast into bite-size pieces. Finely chop the onion and tomatoes. Crush the garlic.',
      'Add the pasta to the boiling water and cook according to package instructions (usually 10-12 minutes) until tender but still has a slight bite. Drain and set aside.',
      'While the pasta cooks, heat 2 tablespoons of oil in a pan over medium-high heat. Season the chicken pieces with salt and pepper, then fry for 5-7 minutes until golden and cooked through (no pink inside).',
      'Remove chicken from the pan. In the same pan, add the onion and garlic. Fry over medium heat for 3 minutes until soft.',
      'Add the chopped tomatoes and mixed herbs. Simmer for 8 minutes, stirring occasionally, until the tomatoes break down into a sauce.',
      'Return the chicken to the pan and stir to coat in the sauce. Cook for 2 more minutes until the chicken is heated through.',
      'Add the drained pasta to the pan and toss everything together. If using cheese, sprinkle on top and stir until melted. Serve hot.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Gluten'],
    thumbnail: 'chicken-pasta',
    storageInstructions: 'Store in an airtight container in the fridge for up to 2 days. Reheat in a pan with a splash of water over medium heat. Pasta is best eaten fresh.',
    leftoverSuggestions: 'Toss leftover pasta in a pan with a little oil over high heat for a quick pasta stir-fry, or serve cold as a pasta salad with mayonnaise.',
  }),

  makeRecipe({
    id: 'st-creamy-chicken-rice',
    title: 'Creamy Chicken and Rice',
    description: 'Tender chicken in a creamy sauce served over rice. A comforting one-pot meal.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 100,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Chicken portions', 800, 'g', 75),
      ing('Rice', 2, 'cups', 15),
      ing('Onions', 1, 'whole', 3),
      ing('Cream', 250, 'ml', 20),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Chicken stock cubes', 1, 'cube', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Mushrooms', 150, 'g', 15, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Cream', substitute: '1 cup milk mixed with 2 tbsp flour' },
      { ingredient: 'Chicken portions', substitute: 'Chicken breast fillets' },
    ],
    instructions: [
      'Cut chicken into pieces if needed. Finely chop the onion and crush the garlic. Rinse the rice under cold water.',
      'Heat 2 tablespoons of oil in a large pot over medium-high heat. Season chicken with salt and pepper, then brown for 3 minutes per side until golden. Remove and set aside.',
      'In the same pot, add the onion and garlic. Fry over medium heat for 3 minutes until soft. If using mushrooms, add them now and cook for 3 minutes.',
      'Add the rice, stock cube and 3 cups of water. Stir well and bring to a boil. Return the chicken to the pot on top of the rice.',
      'Reduce heat to the lowest setting, cover tightly, and simmer for 20 minutes without lifting the lid. Do not stir during this time.',
      'After 20 minutes, check that the rice is tender and the water is absorbed. Pour in the cream and sprinkle with mixed herbs. Stir gently and cook uncovered for 3 minutes until the sauce thickens.',
      'The chicken is cooked when it reaches 75°C internally and the juices run clear. Serve hot, spooning the creamy rice and chicken into bowls.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Dairy'],
    thumbnail: 'creamy-chicken-rice',
    storageInstructions: 'Store in an airtight container in the fridge for up to 2 days. Reheat in a pot with a splash of milk over low heat, stirring gently. Do not boil.',
    leftoverSuggestions: 'Transform leftovers into a chicken rice bake by spreading in a pan, topping with cheese, and heating until melted. Add a side salad for a full meal.',
  }),

  makeRecipe({
    id: 'st-beef-stew',
    title: 'Beef Stew',
    description: 'Slow-cooked beef cubes with potatoes and carrots in a rich gravy. The ultimate winter comfort meal.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Stovetop', 'No-Oven', 'Soup and Stew', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    difficulty: 'Medium',
    estimatedTotalCost: 130,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Beef stew', 1, 'kg', 110),
      ing('Potatoes', 4, 'whole', 12),
      ing('Carrots', 3, 'whole', 9),
      ing('Onions', 2, 'whole', 6),
      ing('Tomatoes', 2, 'whole', 6),
      ing('Garlic', 3, 'cloves', 5, { isStaple: true }),
      ing('Flour', 2, 'tbsp', 2, { isStaple: true }),
      ing('Beef stock cubes', 2, 'cubes', 4, { isStaple: true }),
      ing('Cooking oil', 3, 'tbsp', 3, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 4, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Worcestershire sauce', 1, 'tbsp', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Beef stew', substitute: 'Oxtail or beef shin' },
      { ingredient: 'Flour', substitute: 'Cornflour mixed with cold water' },
    ],
    instructions: [
      'Cut the beef into 3cm cubes if not already portioned. Peel and chop potatoes into large chunks. Slice carrots into thick rounds. Finely dice onions and tomatoes. Crush the garlic.',
      'Toss the beef cubes in flour, salt and pepper until evenly coated. This helps thicken the gravy and gives the meat a good crust.',
      'Heat 3 tablespoons of oil in a large pot over high heat. Brown the beef in batches for 3-4 minutes per batch until deeply coloured. Do not crowd the pot. Remove each batch and set aside.',
      'Reduce heat to medium. Add the onions and garlic to the pot and fry for 4 minutes until soft and golden. Add the tomatoes and cook for 3 minutes until they start breaking down.',
      'Return all the beef to the pot. Add the stock cubes and 4 cups of water. If using Worcestershire sauce, add it now. Bring to a boil, then reduce to low heat.',
      'Cover and simmer gently for 60 minutes, stirring every 20 minutes. After the first hour, add the potatoes and carrots. Continue simmering for 30 more minutes until the beef is fork-tender and the vegetables are soft.',
      'Check that the beef falls apart easily when pressed with a fork. Taste the gravy and adjust seasoning. If the gravy is thin, simmer uncovered for 5-10 minutes to reduce. Serve hot with rice or bread.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: ['Gluten'],
    thumbnail: 'beef-stew',
    storageInstructions: 'Cool completely and store in the fridge for up to 3 days. The flavour improves the next day. Reheat on the stove over medium heat until bubbling throughout.',
    leftoverSuggestions: 'Shred leftover beef and serve the gravy over toast for a quick meal, or use as a filling for a savoury pie. The thickened gravy also works as a sauce for chips.',
  }),

  makeRecipe({
    id: 'st-boerewors-pap',
    title: 'Boerewors and Pap',
    description: 'South African boerewors grilled in a pan, served with soft pap and a tomato relish. A braai classic made indoors.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Family Dinner', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 85,
    equipment: ['Stove', 'Pan', 'Pot'],
    ingredients: [
      ing('Boerewors', 500, 'g', 60),
      ing('Maize meal', 2, 'cups', 15),
      ing('Onions', 1, 'whole', 3),
      ing('Tomatoes', 3, 'whole', 9),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Sugar', 1, 'tsp', 1, { isStaple: true }),
      ing('Vinegar', 1, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Chutney', 2, 'tbsp', 8, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Boerewors', substitute: 'Thick beef sausages' },
      { ingredient: 'Vinegar', substitute: 'Lemon juice' },
    ],
    instructions: [
      'Bring 3 cups of water to a boil in a pot with a pinch of salt. Coil the boerewors into a pan. Dice the onions and tomatoes finely.',
      'Slowly whisk the maize meal into the boiling water. Reduce heat to low, cover, and cook for 15 minutes, stirring every 5 minutes until smooth and thick.',
      'Meanwhile, heat 1 tablespoon of oil in a pan over medium heat. Add the boerewors coil and cook for 5-6 minutes per side until browned and cooked through. The wors is done when it is firm to the touch and no longer pink inside.',
      'Remove the wors from the pan. In the same pan with the remaining juices, add the diced onions and fry for 3 minutes until soft.',
      'Add the tomatoes, sugar and vinegar to the pan. Simmer over medium heat for 10 minutes, stirring occasionally, until the relish thickens.',
      'Taste the relish and season with salt. If using chutney, stir it in for extra sweetness.',
      'Spoon the pap into bowls. Cut the boerewors into pieces and place on top. Spoon the tomato relish over the wors and serve hot.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: [],
    thumbnail: 'boerewors-pap',
    storageInstructions: 'Store wors, pap and relish separately in the fridge for up to 2 days. Reheat wors in a pan over medium heat. Reheat pap with water in the microwave.',
    leftoverSuggestions: 'Slice leftover boerewors and use in a breakfast scramble with eggs. Leftover pap can be sliced and pan-fried until crispy.',
  }),

  makeRecipe({
    id: 'st-sausage-tomato-pasta',
    title: 'Sausage Tomato Pasta',
    description: 'Pan-fried sausages in a rich tomato sauce tossed with pasta. A quick and satisfying weeknight dinner.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Budget', 'Family Dinner', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 80,
    equipment: ['Stove', 'Pot', 'Pan'],
    ingredients: [
      ing('Sausages', 6, 'whole', 55),
      ing('Pasta', 400, 'g', 20),
      ing('Onions', 1, 'whole', 3),
      ing('Tomatoes', 3, 'whole', 9),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    substitutes: [
      { ingredient: 'Sausages', substitute: 'Boerewors or Vienna sausages' },
      { ingredient: 'Tomato paste', substitute: 'Extra fresh tomatoes or a tin of chopped tomatoes' },
    ],
    instructions: [
      'Bring a large pot of salted water to a boil. Slice the sausages into bite-size pieces. Finely chop the onion and tomatoes. Crush the garlic.',
      'Add the pasta to the boiling water and cook for 10-12 minutes until tender. Drain and set aside.',
      'While the pasta cooks, heat 1 tablespoon of oil in a pan over medium-high heat. Add the sausage pieces and fry for 6-8 minutes until browned and cooked through. The sausages are done when they are firm and no longer pink inside.',
      'Remove sausages from the pan. Add the onion and garlic to the same pan and fry over medium heat for 3 minutes until soft.',
      'Add the chopped tomatoes, tomato paste and mixed herbs. Pour in 1 cup of water. Stir well and simmer for 8 minutes, stirring occasionally, until the sauce thickens.',
      'Return the sausage pieces to the pan and stir to coat. Cook for 2 more minutes until heated through. Season with salt and pepper.',
      'Add the drained pasta to the pan and toss everything together. Serve hot in bowls.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: ['Gluten'],
    thumbnail: 'sausage-pasta',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in a pan with a splash of water over medium heat until piping hot.',
    leftoverSuggestions: 'Serve cold leftovers as a pasta salad with a drizzle of olive oil and a squeeze of lemon. The sausage sauce also works well on toast.',
  }),

  makeRecipe({
    id: 'st-mince-vetkoek-filling',
    title: 'Mince Vetkoek Filling',
    description: 'Savoury spiced mince mixture designed as the perfect filling for freshly fried vetkoek. Street food at home.',
    mealCategory: 'Dinner',
    recipeCategories: ['Budget', 'Family Dinner', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: 'Easy',
    estimatedTotalCost: 70,
    equipment: ['Stove', 'Pan', 'Pot'],
    ingredients: [
      ing('Mince', 500, 'g', 55),
      ing('Onions', 2, 'whole', 6),
      ing('Tomatoes', 3, 'whole', 9),
      ing('Curry powder', 2, 'tbsp', 3, { isStaple: true }),
      ing('Garlic', 3, 'cloves', 5, { isStaple: true }),
      ing('Flour', 4, 'cups', 10, { isStaple: true }),
      ing('Yeast', 1, 'packet', 8),
      ing('Sugar', 1, 'tsp', 1, { isStaple: true }),
      ing('Cooking oil', 3, 'cups', 30),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Warm water', 1.5, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Cheese', 100, 'g', 15, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Beef mince', substitute: 'Chicken mince or soya mince' },
      { ingredient: 'Yeast', substitute: 'Baking powder (use 3 tsp and omit rising time)' },
    ],
    instructions: [
      'For the vetkoek dough: combine flour, yeast, sugar and 1 teaspoon of salt in a bowl. Gradually add warm water and mix until a soft dough forms. Knead for 5 minutes until smooth and elastic.',
      'Cover the dough with a damp cloth and leave in a warm place to rise for 1 hour, or until doubled in size.',
      'While the dough rises, make the filling. Finely dice the onions and tomatoes. Crush the garlic. Heat 2 tablespoons of oil in a pan over medium-high heat.',
      'Add the mince and brown for 5-7 minutes, breaking it apart until no pink remains. Add the onions and garlic and fry for 3 minutes until soft.',
      'Stir in the curry powder and cook for 1 minute. Add the tomatoes and 1/2 cup of water. Simmer for 15 minutes over medium-low heat, stirring occasionally, until the sauce thickens. Season with salt and pepper.',
      'Once the dough has risen, punch it down and divide into 8-10 balls. Heat 3 cups of oil in a deep pot over medium heat. Test the oil by dropping a small piece of dough — it should sizzle immediately.',
      'Fry the dough balls for 3-4 minutes per side until golden brown and cooked through. Drain on paper towels. Split open and fill generously with the mince mixture. Add cheese if using. Serve hot.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Gluten'],
    thumbnail: 'vetkoek',
    storageInstructions: 'Store the mince filling in the fridge for up to 3 days. Vetkoek is best eaten fresh but can be stored for 1 day and reheated in the oven or air fryer.',
    leftoverSuggestions: 'Use leftover mince filling on toast for breakfast, or mix with cooked rice for a quick lunch bowl. Leftover dough can be fried as plain vetkoek and served with jam.',
  }),

  makeRecipe({
    id: 'st-egg-fried-rice',
    title: 'Egg Fried Rice',
    description: 'Quick and budget-friendly fried rice with scrambled eggs, onions and soy sauce. Ready in 15 minutes.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Budget', 'Stovetop', 'No-Oven', 'Vegetarian', 'Dinner', 'Leftover'],
    cuisineType: 'Asian',
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    difficulty: 'Easy',
    estimatedTotalCost: 45,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Rice', 2, 'cups', 15),
      ing('Eggs', 3, 'whole', 12),
      ing('Onions', 1, 'whole', 3),
      ing('Soy sauce', 2, 'tbsp', 5, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Peas', 0.5, 'cup', 5, { isOptional: true }),
      ing('Carrots', 1, 'whole', 3, { isOptional: true }),
      ing('Spring onion', 2, 'whole', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Soy sauce', substitute: '1 tsp salt and 1 tsp sugar dissolved in 2 tbsp water' },
      { ingredient: 'Eggs', substitute: 'Tofu, cubed and pan-fried, for a vegan version' },
    ],
    instructions: [
      'Rinse the rice under cold water until the water runs clear. Place in a pot with 3 cups of water and a pinch of salt. Bring to a boil, then reduce to lowest heat, cover, and cook for 18 minutes.',
      'Once cooked, spread the rice on a plate to cool. For best results, use leftover cold rice from the fridge.',
      'Beat the eggs in a bowl with a pinch of salt. Finely dice the onion. If using carrots, dice them small. If using peas, thaw them.',
      'Heat 1 tablespoon of oil in a large pan or wok over high heat. Pour in the beaten eggs and scramble for 1-2 minutes until just set. Remove and set aside.',
      'Add the remaining tablespoon of oil to the pan. Add the onion (and carrots if using) and stir-fry over high heat for 2 minutes until the onion is translucent.',
      'Add the cold rice, breaking up any clumps with a spatula. Stir-fry for 5 minutes over high heat, tossing constantly, until the rice is heated through and slightly crispy. Add peas if using.',
      'Return the scrambled eggs to the pan. Pour the soy sauce over the rice and toss everything together for 1 minute. The rice is ready when it is evenly coated and steaming hot. Garnish with spring onion and serve immediately.',
    ],
    dietaryTags: ['Vegetarian', 'Dairy-Free', 'High-Protein'],
    allergenTags: ['Eggs', 'Soy'],
    thumbnail: 'egg-fried-rice',
    storageInstructions: 'Store in an airtight container in the fridge for up to 2 days. Reheat in a pan over high heat with a splash of water until piping hot throughout. Do not reheat more than once.',
    leftoverSuggestions: 'Add cooked chicken or sausage pieces to leftovers for a heartier meal. Alternatively, shape cold leftover rice into patties and pan-fry until crispy for rice cakes.',
  }),

  makeRecipe({
    id: 'st-chicken-fried-rice',
    title: 'Chicken Fried Rice',
    description: 'Leftover chicken transformed into a quick fried rice with vegetables and soy sauce.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Budget', 'Stovetop', 'No-Oven', 'Dinner', 'Leftover'],
    cuisineType: 'Asian',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 55,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Cooked chicken', 300, 'g', 30),
      ing('Rice', 2, 'cups', 15),
      ing('Eggs', 2, 'whole', 8),
      ing('Onions', 1, 'whole', 3),
      ing('Carrots', 1, 'whole', 3),
      ing('Soy sauce', 3, 'tbsp', 5, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Salt', 1, 'pinch', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Peas', 0.5, 'cup', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Cooked chicken', substitute: 'Cooked ham, prawns, or tofu' },
      { ingredient: 'Soy sauce', substitute: '1 tsp salt dissolved in 2 tbsp water' },
    ],
    instructions: [
      'Cook rice with 3 cups of water and a pinch of salt: bring to a boil, then cover and simmer on lowest heat for 18 minutes. Spread on a plate to cool. Cold rice works best.',
      'Shred the cooked chicken into bite-size pieces. Beat the eggs with a pinch of salt. Finely dice the onion and carrot. Crush the garlic.',
      'Heat 1 tablespoon of oil in a large pan over high heat. Pour in the eggs and scramble for 1 minute until just set. Remove and set aside.',
      'Add the remaining oil to the pan. Add the garlic and onion and stir-fry for 1 minute. Add the diced carrot and stir-fry for 2 minutes until slightly softened.',
      'Add the cold rice, breaking up clumps. Stir-fry over high heat for 5 minutes, tossing constantly, until the rice is heated through and each grain is separate.',
      'Add the shredded chicken, soy sauce and peas if using. Toss everything together for 2 minutes until the chicken is heated through and the rice is evenly coated.',
      'Return the scrambled eggs to the pan and mix gently. The dish is ready when everything is steaming hot. Serve immediately.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: ['Eggs', 'Soy'],
    thumbnail: 'chicken-fried-rice',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in a pan over high heat with a splash of water until steaming hot. Do not reheat more than once.',
    leftoverSuggestions: 'Wrap leftovers in a tortilla with lettuce for a quick lunch wrap. Alternatively, press cold rice into a pan with oil to make a crispy rice crust.',
  }),

  makeRecipe({
    id: 'st-tuna-pasta',
    title: 'Tuna Pasta',
    description: 'Pantry-friendly tuna and pasta in a creamy tomato sauce. Ready in 20 minutes with no fresh ingredients needed.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Budget', 'Lunchbox', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 5,
    cookTime: 20,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 60,
    equipment: ['Stove', 'Pot', 'Pan'],
    ingredients: [
      ing('Tuna', 1, 'can', 25),
      ing('Pasta', 400, 'g', 20),
      ing('Onions', 1, 'whole', 3),
      ing('Tomato paste', 3, 'tbsp', 5, { isStaple: true }),
      ing('Mayonnaise', 3, 'tbsp', 8, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Sweet corn', 1, 'can', 12, { isOptional: true }),
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Tuna', substitute: 'Canned pilchards or salmon' },
      { ingredient: 'Mayonnaise', substitute: '2 tbsp cream or plain yoghurt' },
    ],
    instructions: [
      'Bring a pot of salted water to a boil. Finely dice the onion. Drain the tuna can, reserving a little of the oil.',
      'Add the pasta to the boiling water and cook for 10-12 minutes until tender. Drain and set aside.',
      'While the pasta cooks, heat 1 tablespoon of oil in a pan over medium heat. Add the diced onion and fry for 3 minutes until soft and translucent.',
      'Add the tomato paste and 1 cup of water. Stir well and simmer for 5 minutes until the sauce thickens slightly.',
      'Add the drained tuna to the sauce, breaking it into chunks with a spoon. Stir in the mayonnaise until the sauce is smooth and creamy. If using sweet corn, drain and add now.',
      'Simmer for 3 minutes, stirring gently to avoid breaking up the tuna too much. Season with salt and pepper to taste.',
      'Add the drained pasta to the pan and toss to coat. If using cheese, sprinkle on top and stir until melted. Serve hot.',
    ],
    dietaryTags: ['High-Protein', 'Pescatarian'],
    allergenTags: ['Fish', 'Eggs'],
    thumbnail: 'tuna-pasta',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in a pan with a splash of water over medium heat. Tuna pasta can also be served cold as a pasta salad.',
    leftoverSuggestions: 'Serve cold leftovers as a pasta salad with extra mayonnaise and a squeeze of lemon. Alternatively, spread on toast and top with cheese for a tuna melt.',
  }),

  makeRecipe({
    id: 'st-fish-cakes',
    title: 'Fish Cakes',
    description: 'Crispy pan-fried fish cakes made with canned fish and mashed potato. Budget-friendly and filling.',
    mealCategory: 'Dinner',
    recipeCategories: ['Budget', 'Family Dinner', 'Lunchbox', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'Medium',
    estimatedTotalCost: 55,
    equipment: ['Stove', 'Pot', 'Pan'],
    ingredients: [
      ing('Fish', 1, 'can', 25),
      ing('Potatoes', 4, 'whole', 12),
      ing('Onions', 1, 'whole', 3),
      ing('Eggs', 1, 'whole', 4),
      ing('Flour', 0.5, 'cup', 3, { isStaple: true }),
      ing('Breadcrumbs', 1, 'cup', 5, { isStaple: true }),
      ing('Cooking oil', 0.5, 'cup', 8),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Curry powder', 1, 'tsp', 2, { isOptional: true, isStaple: true }),
      ing('Lemon', 0.5, 'whole', 4, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Canned fish', substitute: 'Fresh hake, cooked and flaked' },
      { ingredient: 'Breadcrumbs', substitute: 'Crushed crackers or maize meal' },
    ],
    instructions: [
      'Peel the potatoes and cut into chunks. Place in a pot, cover with water and add salt. Boil for 15-20 minutes until fork-tender. Drain and mash until smooth. Set aside to cool.',
      'While the potatoes cook, drain the canned fish and remove any large bones. Flake the fish with a fork. Finely dice the onion.',
      'In a bowl, combine the cooled mashed potato, flaked fish, diced onion, egg, flour, salt and pepper. If using curry powder, add it now. Mix until well combined.',
      'Shape the mixture into 8-10 flat patties about 2cm thick. Press firmly so they hold together.',
      'Place the breadcrumbs on a plate. Coat each patty in breadcrumbs, pressing gently to adhere.',
      'Heat 0.5 cups of oil in a pan over medium-high heat. Test the oil by dropping a breadcrumb — it should sizzle. Fry the fish cakes for 3-4 minutes per side until golden brown and crispy.',
      'The fish cakes are cooked when they are golden on both sides and heated through. Drain on paper towels. Serve hot with lemon wedges and a side salad or chutney.',
    ],
    dietaryTags: ['Pescatarian', 'High-Protein'],
    allergenTags: ['Fish', 'Eggs', 'Gluten'],
    thumbnail: 'fish-cakes',
    storageInstructions: 'Store cooked fish cakes in the fridge for up to 2 days. Reheat in a pan over medium heat for 3 minutes per side. Uncooked patties can be frozen for up to 1 month.',
    leftoverSuggestions: 'Serve cold leftover fish cakes in a bread roll with mayonnaise and lettuce for a fish cake burger. Alternatively, break up and mix into a pasta salad.',
  }),

  makeRecipe({
    id: 'st-potato-egg-hash',
    title: 'Potato and Egg Hash',
    description: 'Crispy pan-fried potatoes with scrambled eggs and onions. A hearty breakfast or quick dinner.',
    mealCategory: 'Breakfast',
    recipeCategories: ['Quick Weekday', 'Budget', 'Stovetop', 'No-Oven', 'Vegetarian', 'Breakfast', 'Leftover'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 20,
    servings: 3,
    difficulty: 'Easy',
    estimatedTotalCost: 35,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Potatoes', 3, 'whole', 9),
      ing('Eggs', 4, 'whole', 16),
      ing('Onions', 1, 'whole', 3),
      ing('Cooking oil', 3, 'tbsp', 3, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
      ing('Tomatoes', 1, 'whole', 3, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Eggs', substitute: 'Tofu, crumbled and scrambled' },
    ],
    instructions: [
      'Peel the potatoes and dice into small 1cm cubes. Finely dice the onion. Beat the eggs in a bowl with salt and pepper.',
      'Heat 2 tablespoons of oil in a pan over medium-high heat. Add the diced potatoes and cook for 10 minutes, stirring every 2 minutes, until golden and crispy on all sides.',
      'Add the diced onion to the potatoes and cook for 3 minutes until the onion is soft and translucent.',
      'Push the potato mixture to one side of the pan. Add the remaining tablespoon of oil to the empty side and pour in the beaten eggs.',
      'Let the eggs set for 30 seconds, then gently scramble with a spatula for 1-2 minutes until just set but still soft.',
      'Mix the scrambled eggs with the potato hash in the pan. If using cheese, sprinkle on top and let it melt for 1 minute. If using tomatoes, dice and stir in.',
      'Cook for 1 more minute until everything is heated through. The potatoes should be crispy and the eggs tender. Serve immediately.',
    ],
    dietaryTags: ['Vegetarian', 'High-Protein'],
    allergenTags: ['Eggs', 'Dairy'],
    thumbnail: 'potato-hash',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in a pan over medium heat until the potatoes are crispy again and the eggs are steaming hot.',
    leftoverSuggestions: 'Spoon leftovers into a wrap with a drizzle of sauce for a breakfast burrito. Alternatively, serve cold on toast with a slice of cheese.',
  }),

  makeRecipe({
    id: 'st-tomato-bredie',
    title: 'Tomato Bredie',
    description: 'Traditional South African lamb and tomato stew, slow-cooked until the meat falls off the bone.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Stovetop', 'No-Oven', 'Soup and Stew', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 90,
    servings: 6,
    difficulty: 'Medium',
    estimatedTotalCost: 140,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Beef stew', 1, 'kg', 110),
      ing('Tomatoes', 6, 'whole', 18),
      ing('Onions', 2, 'whole', 6),
      ing('Potatoes', 3, 'whole', 9),
      ing('Garlic', 3, 'cloves', 5, { isStaple: true }),
      ing('Cinnamon', 1, 'tsp', 2, { isStaple: true }),
      ing('Sugar', 1, 'tsp', 1, { isStaple: true }),
      ing('Cooking oil', 3, 'tbsp', 3, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 2, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Chilli', 1, 'whole', 3, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Beef stew', substitute: 'Lamb rib chops or mutton pieces' },
      { ingredient: 'Cinnamon', substitute: '1 bay leaf' },
    ],
    instructions: [
      'Cut the beef into 3cm cubes. Finely chop the onions and tomatoes. Crush the garlic. Peel and quarter the potatoes.',
      'Heat 3 tablespoons of oil in a large pot over high heat. Season the beef with salt and pepper, then brown in batches for 3-4 minutes per batch until deeply coloured. Set aside.',
      'Reduce heat to medium. Add the onions and garlic to the pot and fry for 4 minutes until soft and golden.',
      'Add the chopped tomatoes, cinnamon, sugar and a pinch of salt. Cook for 8 minutes, stirring occasionally, until the tomatoes break down into a thick sauce.',
      'Return the beef to the pot. Add 2 cups of water and bring to a boil. Reduce heat to low, cover, and simmer for 60 minutes, stirring every 20 minutes.',
      'After 60 minutes, add the quartered potatoes. Cover and simmer for 25 more minutes until the beef is fork-tender and the potatoes are soft.',
      'The bredie is ready when the meat falls apart easily and the sauce is thick and rich. Taste and adjust seasoning. Serve hot with rice or bread.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: [],
    thumbnail: 'tomato-bredie',
    storageInstructions: 'Store in the fridge for up to 3 days. Like all bredies, the flavour improves the next day. Reheat on the stove over medium heat until bubbling.',
    leftoverSuggestions: 'Shred leftover meat and use as a filling for sandwiches or pies. The thick tomato sauce is excellent over chips or as a base for a pasta sauce.',
  }),

  makeRecipe({
    id: 'st-veg-soup',
    title: 'Bean-Free Vegetable Soup',
    description: 'A light and nourishing vegetable soup with potatoes, carrots and tomatoes. No beans required.',
    mealCategory: 'Dinner',
    recipeCategories: ['Budget', 'One-Pot', 'Stovetop', 'No-Oven', 'Vegetarian', 'Soup and Stew', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 45,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Potatoes', 3, 'whole', 9),
      ing('Carrots', 3, 'whole', 9),
      ing('Onions', 1, 'whole', 3),
      ing('Tomatoes', 3, 'whole', 9),
      ing('Butternut', 200, 'g', 8),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Vegetable stock cubes', 2, 'cubes', 4, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 5, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Cabbage', 1, 'cup', 4, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Butternut', substitute: 'Sweet potato or pumpkin' },
      { ingredient: 'Vegetable stock cubes', substitute: 'Chicken stock cubes' },
    ],
    instructions: [
      'Peel and dice the potatoes, carrots and butternut into 2cm cubes. Finely chop the onion and tomatoes. Crush the garlic.',
      'Heat 1 tablespoon of oil in a large pot over medium heat. Add the onion and garlic and fry for 3 minutes until soft.',
      'Add the chopped tomatoes and cook for 4 minutes, stirring occasionally, until they soften and release their juices.',
      'Add the potatoes, carrots and butternut. Stir to coat in the tomato mixture. Add the stock cubes, mixed herbs and 5 cups of water.',
      'Bring to a boil, then reduce heat to low. Cover and simmer for 20 minutes, stirring every 10 minutes, until all the vegetables are tender when pierced with a fork.',
      'If using cabbage, add it in the last 5 minutes of cooking. Taste the soup and season with salt and pepper.',
      'The soup is ready when all vegetables are soft and the broth is flavourful. Serve hot in bowls with fresh bread on the side.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan', 'Dairy-Free', 'Gluten-Free'],
    allergenTags: [],
    thumbnail: 'veg-soup',
    storageInstructions: 'Store in the fridge for up to 3 days. Reheat on the stove over medium heat until steaming hot. Can also be frozen for up to 1 month.',
    leftoverSuggestions: 'Blend leftover soup until smooth for a creamy vegetable soup. Alternatively, drain the vegetables and serve them over rice with the broth on the side.',
  }),

  makeRecipe({
    id: 'st-chicken-noodle-soup',
    title: 'Chicken Noodle Soup',
    description: 'Comforting chicken soup with noodles, carrots and a clear broth. Perfect for cold days or when feeling unwell.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'One-Pot', 'Stovetop', 'No-Oven', 'Soup and Stew', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 75,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Chicken breast', 400, 'g', 50),
      ing('Noodles', 200, 'g', 12),
      ing('Carrots', 2, 'whole', 6),
      ing('Onions', 1, 'whole', 3),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Ginger', 1, 'tsp', 3, { isStaple: true }),
      ing('Chicken stock cubes', 2, 'cubes', 4, { isStaple: true }),
      ing('Cooking oil', 1, 'tbsp', 1, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 5, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Spring onion', 2, 'whole', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Chicken breast', substitute: 'Chicken portions or leftover cooked chicken' },
      { ingredient: 'Noodles', substitute: 'Any pasta — spaghetti broken into short pieces works well' },
    ],
    instructions: [
      'Slice the chicken breast into thin strips. Peel and slice the carrots into thin rounds. Finely chop the onion. Crush the garlic and grate the ginger.',
      'Heat 1 tablespoon of oil in a large pot over medium-high heat. Add the chicken strips and fry for 3-4 minutes until lightly browned on all sides.',
      'Add the onion, garlic and ginger. Fry for 2 minutes until the onion is soft and fragrant.',
      'Add the sliced carrots, stock cubes and 5 cups of water. Bring to a boil, then reduce heat to medium.',
      'Simmer uncovered for 15 minutes, skimming off any foam that rises to the top. The chicken is cooked when it is white throughout with no pink.',
      'Add the noodles and cook for 5-8 minutes (or according to package time) until tender. Stir occasionally to prevent sticking.',
      'Taste the broth and season with salt and pepper. The soup is ready when the noodles are tender, the chicken is cooked through and the broth is flavourful. Garnish with spring onion and serve hot.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free'],
    allergenTags: ['Gluten'],
    thumbnail: 'chicken-soup',
    storageInstructions: 'Store the broth and noodles separately in the fridge for up to 2 days. Noodles will absorb the broth if stored together. Reheat together on the stove until bubbling.',
    leftoverSuggestions: 'Strain leftover broth and use as a base for other soups or stews. Leftover chicken and vegetables can be added to fried rice.',
  }),

  makeRecipe({
    id: 'st-macaroni-mince',
    title: 'Macaroni and Mince',
    description: 'Macaroni pasta baked in a rich mince and tomato sauce. A South African school-night classic.',
    mealCategory: 'Dinner',
    recipeCategories: ['Quick Weekday', 'Budget', 'Family Dinner', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 30,
    servings: 5,
    difficulty: 'Easy',
    estimatedTotalCost: 80,
    equipment: ['Stove', 'Pot', 'Pan'],
    ingredients: [
      ing('Mince', 500, 'g', 55),
      ing('Macaroni', 400, 'g', 20),
      ing('Onions', 1, 'whole', 3),
      ing('Tomatoes', 3, 'whole', 9),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Garlic', 2, 'cloves', 3, { isStaple: true }),
      ing('Mixed herbs', 1, 'tsp', 2, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Cheese', 100, 'g', 15, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Macaroni', substitute: 'Any small pasta shape' },
      { ingredient: 'Cheese', substitute: 'Skip if unavailable — the dish works without it' },
    ],
    instructions: [
      'Bring a large pot of salted water to a boil. Finely dice the onion and tomatoes. Crush the garlic.',
      'Add the macaroni to the boiling water and cook for 10-12 minutes until tender. Drain and set aside.',
      'While the pasta cooks, heat 2 tablespoons of oil in a pan over medium-high heat. Add the mince and brown for 5-7 minutes, breaking it apart until no pink remains.',
      'Add the diced onion and garlic to the mince. Fry for 3 minutes until the onion is soft.',
      'Add the chopped tomatoes, tomato paste, mixed herbs and 1 cup of water. Stir well and simmer for 12 minutes over medium-low heat, stirring occasionally, until the sauce thickens.',
      'Season with salt and pepper. The sauce is ready when it coats the mince and has a gravy-like consistency.',
      'Combine the cooked macaroni and mince sauce in a large pot or serving dish. Toss until the pasta is evenly coated. If using cheese, sprinkle on top and stir until melted. Serve hot.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Gluten', 'Dairy'],
    thumbnail: 'macaroni-mince',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in a pan with a splash of water over medium heat until piping hot throughout.',
    leftoverSuggestions: 'Spread leftovers in a pan, top with extra cheese and heat until melted for a quick macaroni bake. Alternatively, serve cold as a pasta salad.',
  }),

  makeRecipe({
    id: 'st-cottage-pie',
    title: 'Cottage Pie',
    description: 'Beef mince topped with creamy mashed potato. Traditionally baked, but works on the stovetop too.',
    mealCategory: 'Dinner',
    recipeCategories: ['Family Dinner', 'Stovetop', 'Dinner'],
    cuisineType: 'British',
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: 'Medium',
    estimatedTotalCost: 95,
    equipment: ['Stove', 'Pot', 'Pan'],
    ingredients: [
      ing('Mince', 500, 'g', 55),
      ing('Potatoes', 6, 'whole', 18),
      ing('Onions', 1, 'whole', 3),
      ing('Carrots', 2, 'whole', 6),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Beef stock cubes', 1, 'cube', 2, { isStaple: true }),
      ing('Milk', 0.25, 'cup', 3, { isStaple: true }),
      ing('Butter', 2, 'tbsp', 4, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 2, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Cheese', 50, 'g', 10, { isOptional: true }),
      ing('Peas', 0.5, 'cup', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Beef mince', substitute: 'Lamb mince for a shepherd\'s pie' },
      { ingredient: 'Milk', substitute: 'Water or stock for dairy-free mash' },
    ],
    instructions: [
      'Peel the potatoes and cut into chunks. Place in a pot, cover with salted water and boil for 15-20 minutes until fork-tender. Finely dice the onion and carrots.',
      'While the potatoes boil, heat 2 tablespoons of oil in a pan over medium-high heat. Add the mince and brown for 5-7 minutes until no pink remains.',
      'Add the diced onion and carrots to the mince. Fry for 4 minutes until the onion is soft.',
      'Add the tomato paste, stock cube and 1.5 cups of water. If using peas, add now. Simmer over medium-low heat for 15 minutes, stirring occasionally, until the sauce thickens.',
      'Drain the potatoes and mash with the milk and butter until smooth and creamy. Season with salt and pepper.',
      'Taste the mince mixture and adjust seasoning. It should be thick and savoury.',
      'Spread the mince mixture in a pot or pan. Top with the mashed potato, spreading it evenly. If using cheese, sprinkle on top. Cover and cook over very low heat for 10 minutes until the top is set and the filling is bubbling. Serve hot.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Dairy', 'Gluten'],
    thumbnail: 'cottage-pie',
    storageInstructions: 'Store in the fridge for up to 3 days. Reheat in a covered pan over low heat for 15 minutes until bubbling throughout. Can also be frozen for up to 1 month.',
    leftoverSuggestions: 'Shape cold leftovers into patties, coat in flour and pan-fry until crispy for cottage pie cakes. Alternatively, use the mince filling as a topping for toast.',
  }),

  makeRecipe({
    id: 'st-chicken-livers',
    title: 'Chicken Livers in Garlic Sauce',
    description: 'Tender chicken livers in a rich garlic and herb sauce. A South African starter or main served with bread.',
    mealCategory: 'Dinner',
    recipeCategories: ['Budget', 'Stovetop', 'No-Oven', 'Dinner'],
    cuisineType: 'South African',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 50,
    equipment: ['Stove', 'Pan'],
    ingredients: [
      ing('Chicken livers', 500, 'g', 35),
      ing('Onions', 2, 'whole', 6),
      ing('Garlic', 5, 'cloves', 5, { isStaple: true }),
      ing('Tomato paste', 2, 'tbsp', 5, { isStaple: true }),
      ing('Curry powder', 1, 'tsp', 2, { isStaple: true }),
      ing('Cooking oil', 2, 'tbsp', 2, { isStaple: true }),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 1, 'cup', 0),
    ],
    optionalIngredients: [
      ing('Peri-peri', 1, 'tsp', 5, { isOptional: true }),
      ing('Cream', 0.25, 'cup', 5, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Chicken livers', substitute: 'Chicken hearts or gizzards' },
    ],
    instructions: [
      'Rinse the chicken livers under cold water and trim away any connective tissue. Cut large livers in half. Finely slice the onions. Crush or mince all the garlic.',
      'Heat 2 tablespoons of oil in a pan over medium-high heat. Add the onions and fry for 4 minutes until golden and soft.',
      'Add the garlic and curry powder. Stir for 30 seconds until fragrant, being careful not to burn the garlic.',
      'Add the chicken livers to the pan. Fry for 5 minutes, stirring frequently, until the livers are browned on all sides but still slightly pink inside. Do not overcook or they become tough.',
      'Add the tomato paste and 1 cup of water. Stir well. If using peri-peri, add it now. Reduce heat to medium and simmer for 8 minutes, stirring occasionally, until the sauce thickens.',
      'If using cream, stir it in during the last 2 minutes of cooking for a richer sauce.',
      'The livers are cooked when they are firm but still tender (no raw red inside, slight pink is safe). Season with salt and pepper. Serve hot with fresh bread to soak up the sauce.',
    ],
    dietaryTags: ['High-Protein', 'Dairy-Free', 'Low-Carb'],
    allergenTags: [],
    thumbnail: 'chicken-livers',
    storageInstructions: 'Store in the fridge for up to 2 days. Reheat in a pan over medium heat until bubbling. Livers are best eaten fresh as they toughen when reheated.',
    leftoverSuggestions: 'Spread leftover livers and sauce on toast for a quick snack. Alternatively, toss with cooked pasta for a rich garlic liver pasta.',
  }),

  makeRecipe({
    id: 'st-chicken-mayo-sandwich',
    title: 'Chicken Mayonnaise Sandwich',
    description: 'Classic chicken and mayo sandwich filling. Perfect for lunchboxes or a quick lunch.',
    mealCategory: 'Lunch',
    recipeCategories: ['Quick Weekday', 'Lunchbox', 'Stovetop', 'No-Oven', 'Lunch'],
    cuisineType: 'South African',
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    estimatedTotalCost: 45,
    equipment: ['Stove', 'Pot'],
    ingredients: [
      ing('Chicken breast', 400, 'g', 50),
      ing('Bread', 8, 'slices', 16),
      ing('Mayonnaise', 4, 'tbsp', 10, { isStaple: true }),
      ing('Onions', 0.5, 'whole', 2),
      ing('Salt', 1, 'tsp', 1, { isStaple: true }),
      ing('Pepper', 1, 'tsp', 1, { isStaple: true }),
      ing('Water', 3, 'cups', 0),
    ],
    optionalIngredients: [
      ing('Lettuce', 4, 'leaves', 5, { isOptional: true }),
      ing('Tomatoes', 1, 'whole', 3, { isOptional: true }),
    ],
    substitutes: [
      { ingredient: 'Mayonnaise', substitute: 'Plain yoghurt or cream cheese' },
      { ingredient: 'Chicken breast', substitute: 'Leftover cooked chicken' },
    ],
    instructions: [
      'Place the chicken breast in a pot and cover with water. Add salt. Bring to a boil over high heat, then reduce to medium-low and simmer for 15 minutes until the chicken is cooked through (no pink inside, juices run clear).',
      'Remove the chicken from the pot and let it cool for 10 minutes until easy to handle. Finely dice the onion.',
      'Shred the cooled chicken using two forks, or dice into small pieces. Place in a mixing bowl.',
      'Add the mayonnaise, diced onion, salt and pepper to the shredded chicken. Mix until well combined and creamy.',
      'If using tomatoes, slice them thinly. If using lettuce, wash and dry the leaves.',
      'Lay out the bread slices. Spoon the chicken mayo mixture onto 4 slices, spreading evenly.',
      'Top with lettuce and tomato slices if using, then place the remaining bread slices on top. Cut each sandwich in half and serve.',
    ],
    dietaryTags: ['High-Protein'],
    allergenTags: ['Gluten', 'Eggs'],
    thumbnail: 'chicken-mayo',
    storageInstructions: 'Store the chicken mayo filling separately from the bread in the fridge for up to 2 days. Assemble sandwiches fresh to prevent soggy bread.',
    leftoverSuggestions: 'Use leftover chicken mayo filling as a jacket potato topping, on crackers as a snack, or mixed into cooked pasta for a quick chicken pasta salad.',
  }),
];
